"""C sources of the E2E core library (docs/e2e-profile.md), shared by every node.

Kept apart from gen_c.py so the generator logic stays readable. Behaviour must
match e2e.py exactly (tests/test_c_code.py cross-checks both).
"""

BANNER = """/*
 * GENERATED by moto-vehicle-defs tools/codegen from {source}. DO NOT EDIT.
 * Regenerate with `make gen`.
 */
"""

E2E_CORE_H = (
    BANNER.format(source="tools/codegen (docs/e2e-profile.md)")
    + r"""
#ifndef MOTO_E2E_H
#define MOTO_E2E_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Platform E2E scheme (D-005, docs/e2e-profile.md):
 *   byte 0          CRC-8/SAE-J1850 (poly 0x1D, init 0xFF, xorout 0xFF)
 *                   over DataID low byte, DataID high byte, bytes 1..size-1
 *   byte 1 bits 0-3 alive counter 0..15, +1 per transmission, wraps
 * The DataID is never transmitted. */

#define MOTO_E2E_CRC_OFFSET     (0u)
#define MOTO_E2E_COUNTER_OFFSET (1u)
#define MOTO_E2E_COUNTER_MASK   (0x0Fu)

typedef enum {
    MOTO_E2E_OK = 0,             /* new data, counter +1                         */
    MOTO_E2E_OK_SOME_LOST = 1,   /* new data, counter jump within max_delta      */
    MOTO_E2E_INITIAL = 2,        /* first valid frame after init/timeout: resync */
    MOTO_E2E_REPEATED = 3,       /* same counter again: sender frozen/duplicated */
    MOTO_E2E_WRONG_SEQUENCE = 4, /* counter jump > max_delta                     */
    MOTO_E2E_WRONG_CRC = 5,      /* corrupted or wrong DataID (masquerade)       */
    MOTO_E2E_NO_NEW_DATA = 6,    /* timeout expired or never received            */
    MOTO_E2E_BAD_ARGUMENT = 7
} moto_e2e_status_t;

typedef struct {
    uint8_t counter;
} moto_e2e_tx_state_t;

typedef struct {
    uint32_t last_rx_ms;
    uint8_t last_counter;
    bool synced;
} moto_e2e_rx_state_t;

/* Zero-initialised states are valid initial states. */
void moto_e2e_tx_init(moto_e2e_tx_state_t *state);
void moto_e2e_rx_init(moto_e2e_rx_state_t *state);

uint8_t moto_e2e_crc(uint16_t data_id, const uint8_t *data, size_t size);

/* Sender: call after packing the payload, right before transmission. */
moto_e2e_status_t moto_e2e_protect(uint16_t data_id, uint8_t *data, size_t size,
                                   moto_e2e_tx_state_t *state);

/* Receiver: call for every received frame of the message. Only OK and
 * OK_SOME_LOST allow the payload to be used (see moto_e2e_is_valid). A frame
 * arriving more than timeout_ms after the last valid one resyncs (INITIAL). */
moto_e2e_status_t moto_e2e_check(uint16_t data_id, uint8_t max_delta, uint32_t timeout_ms,
                                 const uint8_t *data, size_t size, moto_e2e_rx_state_t *state,
                                 uint32_t now_ms);

/* Receiver: call periodically (at least once per cycle). Returns NO_NEW_DATA
 * once timeout_ms has passed without a valid frame, and forces a resync. */
moto_e2e_status_t moto_e2e_check_timeout(moto_e2e_rx_state_t *state, uint32_t timeout_ms,
                                         uint32_t now_ms);

bool moto_e2e_is_valid(moto_e2e_status_t status);

#ifdef __cplusplus
}
#endif

#endif /* MOTO_E2E_H */
"""
)

E2E_CORE_C = (
    BANNER.format(source="tools/codegen (docs/e2e-profile.md)")
    + r"""
#include "moto_e2e.h"

static uint8_t crc8_update(uint8_t crc, uint8_t byte)
{
    uint8_t value = (uint8_t)(crc ^ byte);
    uint8_t bit;

    for (bit = 0u; bit < 8u; bit++) {
        if ((value & 0x80u) != 0u) {
            value = (uint8_t)((uint8_t)(value << 1u) ^ 0x1Du);
        } else {
            value = (uint8_t)(value << 1u);
        }
    }
    return value;
}

void moto_e2e_tx_init(moto_e2e_tx_state_t *state)
{
    if (state != NULL) {
        state->counter = 0u;
    }
}

void moto_e2e_rx_init(moto_e2e_rx_state_t *state)
{
    if (state != NULL) {
        state->last_rx_ms = 0u;
        state->last_counter = 0u;
        state->synced = false;
    }
}

uint8_t moto_e2e_crc(uint16_t data_id, const uint8_t *data, size_t size)
{
    uint8_t crc = 0xFFu;
    size_t i;

    crc = crc8_update(crc, (uint8_t)(data_id & 0xFFu));
    crc = crc8_update(crc, (uint8_t)((data_id >> 8u) & 0xFFu));
    if (data != NULL) {
        for (i = 1u; i < size; i++) {
            crc = crc8_update(crc, data[i]);
        }
    }
    return (uint8_t)(crc ^ 0xFFu);
}

moto_e2e_status_t moto_e2e_protect(uint16_t data_id, uint8_t *data, size_t size,
                                   moto_e2e_tx_state_t *state)
{
    if ((data == NULL) || (state == NULL) || (size < 2u)) {
        return MOTO_E2E_BAD_ARGUMENT;
    }
    data[MOTO_E2E_COUNTER_OFFSET] =
        (uint8_t)((data[MOTO_E2E_COUNTER_OFFSET] & 0xF0u) | (state->counter & MOTO_E2E_COUNTER_MASK));
    data[MOTO_E2E_CRC_OFFSET] = moto_e2e_crc(data_id, data, size);
    state->counter = (uint8_t)((state->counter + 1u) & MOTO_E2E_COUNTER_MASK);
    return MOTO_E2E_OK;
}

moto_e2e_status_t moto_e2e_check(uint16_t data_id, uint8_t max_delta, uint32_t timeout_ms,
                                 const uint8_t *data, size_t size, moto_e2e_rx_state_t *state,
                                 uint32_t now_ms)
{
    uint8_t counter;
    uint8_t delta;

    if ((data == NULL) || (state == NULL) || (size < 2u) || (max_delta < 1u) ||
        (max_delta > 14u)) {
        return MOTO_E2E_BAD_ARGUMENT;
    }
    if (data[MOTO_E2E_CRC_OFFSET] != moto_e2e_crc(data_id, data, size)) {
        return MOTO_E2E_WRONG_CRC;
    }
    counter = (uint8_t)(data[MOTO_E2E_COUNTER_OFFSET] & MOTO_E2E_COUNTER_MASK);
    if (state->synced && ((uint32_t)(now_ms - state->last_rx_ms) > timeout_ms)) {
        state->synced = false; /* stalled sender: never resume as OK */
    }
    if (!state->synced) {
        state->synced = true;
        state->last_counter = counter;
        state->last_rx_ms = now_ms;
        return MOTO_E2E_INITIAL;
    }
    delta = (uint8_t)((uint8_t)(counter - state->last_counter) & MOTO_E2E_COUNTER_MASK);
    if (delta == 0u) {
        return MOTO_E2E_REPEATED;
    }
    state->last_counter = counter;
    if (delta > max_delta) {
        return MOTO_E2E_WRONG_SEQUENCE;
    }
    state->last_rx_ms = now_ms;
    return (delta == 1u) ? MOTO_E2E_OK : MOTO_E2E_OK_SOME_LOST;
}

moto_e2e_status_t moto_e2e_check_timeout(moto_e2e_rx_state_t *state, uint32_t timeout_ms,
                                         uint32_t now_ms)
{
    if (state == NULL) {
        return MOTO_E2E_BAD_ARGUMENT;
    }
    if (!state->synced) {
        return MOTO_E2E_NO_NEW_DATA;
    }
    if ((uint32_t)(now_ms - state->last_rx_ms) > timeout_ms) {
        state->synced = false;
        return MOTO_E2E_NO_NEW_DATA;
    }
    return MOTO_E2E_OK;
}

bool moto_e2e_is_valid(moto_e2e_status_t status)
{
    return (status == MOTO_E2E_OK) || (status == MOTO_E2E_OK_SOME_LOST);
}
"""
)
