"""C code generation: per-node cantools pack/unpack, E2E and the CL250 DID table.

All generated C is C99, uses only fixed-width types, no dynamic memory, no
recursion and no string/DBC parsing (platform invariant 5).
"""

from __future__ import annotations

import re
from typing import Any

from cantools.database.can import Database, Message
from cantools.database.can.c_source import camel_to_snake_case, generate

from . import config
from .c_e2e_templates import BANNER, E2E_CORE_C, E2E_CORE_H
from .dbc_checks import cycle_time_ms, e2e_data_id, is_e2e_protected
from .yaml_checks import DID_PRIORITIES, SCAN_REQUEST_MAX, limit_scope

_CANTOOLS_DATE_RE = re.compile(r"(generated by cantools version \S+) .*?\.$", re.MULTILINE)


def _strip_date(text: str) -> str:
    """cantools stamps the generation time; drop it so `make gen` is reproducible."""
    return _CANTOOLS_DATE_RE.sub(r"\1.", text)


# cantools has no MISRA mode, so its platform.c is rewritten where it breaks a required
# MISRA C:2012 rule (D-046 item 2). Every rewrite keeps the behaviour.
_MISRA_FIXUPS: tuple[tuple[re.Pattern[str], str], ...] = (
    # 17.7: the pointer returned by memset() is not used
    (re.compile(r"^([ \t]*)memset\(", re.MULTILINE), r"\1(void)memset("),
    # 15.6: the NULL guard in *_init() gets a compound statement
    (
        re.compile(r"^([ \t]*)if \((.+)\) return (.+);$", re.MULTILINE),
        r"\1if (\2) {\n\1    return \3;\n\1}",
    ),
    # 10.8: widen the 8-bit operand before masking instead of casting the composite
    (re.compile(r"\((uint(?:16|32|64)_t)\)\(value & mask\)"), r"((\1)value & mask)"),
)


def _misra_fixups(source: str) -> str:
    for pattern, replacement in _MISRA_FIXUPS:
        source = pattern.sub(replacement, source)
    return source


# cantools' <msg>_<signal>_encode() truncates (value - offset) / scale toward zero, so a
# float quotient just below an integer loses one raw step (0.010 V -> 9 mV), while the
# cantools Python reference rounds (D-056). The body is rewritten to round to nearest,
# halves away from zero (Python rounds halves to even: they differ only on exact ties;
# `raw + 0.5f` may also round a value within one ulp below a tie up, inside the error the
# float quotient already has). It also saturates at the C type's range and maps NaN to 0,
# so no input converts out of range (undefined in C): an out-of-range value gives the type
# limit instead of a wrapped number. The physical range stays the caller's check
# (is_in_phys_range()). The cast applies to a plain object, not a composite expression
# (MISRA C:2012 10.8, which the cppcheck addon does not check for float operands).
_ENCODE_RE = re.compile(
    r"^(?P<type>(?P<u>u?)int(?P<bits>8|16|32|64)_t) (?P<name>\w+_encode)\(float value\)\n"
    r"\{\n    return \((?P=type)\)\((?P<expr>[^;\n]+)\);\n\}$",
    re.MULTILINE,
)


def _f32_toward_zero(n: int) -> int:
    """The float32 value nearest to n on the side of zero (n itself below 2^24)."""
    shift = max(0, abs(n).bit_length() - 24)
    magnitude = (abs(n) >> shift) << shift
    return magnitude if n >= 0 else -magnitude


def _round_encode(found: re.Match[str]) -> str:
    ctype, name, expr, bits = found["type"], found["name"], found["expr"], int(found["bits"])
    # Two separate ifs, not an else-if chain: NaN fails both and stays 0 (cppcheck does
    # not model NaN and would call the second branch of a chain always true).
    if found["u"]:
        top = _f32_toward_zero((1 << bits) - 1)
        branches = (
            "    if (raw > 0.0f) { /* raw <= 0 or NaN: 0 */\n"
            f"        rounded = (raw >= {top}.0f) ? {top}.0f : (raw + 0.5f);\n    }}\n"
        )
    else:
        top = _f32_toward_zero((1 << (bits - 1)) - 1)
        bottom = -(1 << (bits - 1))
        branches = (
            "    if (raw >= 0.0f) {\n"
            f"        rounded = (raw >= {top}.0f) ? {top}.0f : (raw + 0.5f);\n    }}\n"
            "    if (raw < 0.0f) { /* NaN fails both: 0 */\n"
            f"        rounded = (raw <= {bottom}.0f) ? {bottom}.0f : (raw - 0.5f);\n    }}\n"
        )
    return (
        f"{ctype} {name}(float value)\n{{\n    const float raw = {expr};\n"
        f"    float rounded = 0.0f;\n\n{branches}\n    return ({ctype})rounded;\n}}"
    )


def _encode_rounding(source: str, header: str) -> str:
    rounded, count = _ENCODE_RE.subn(_round_encode, source)
    expected = len(re.findall(r"\w+_encode\(float value\);", header))
    if count != expected:  # a cantools upgrade changed the body: never ship truncation
        raise ValueError(f"encode rounding: rewrote {count} of {expected} encode functions")
    return rounded


def _sends(target: config.CTarget, msg: Message) -> bool:
    return target.all_messages or target.node in msg.senders


def _receives(target: config.CTarget, msg: Message) -> bool:
    return target.all_messages or target.node in msg.receivers


def generate_platform_c(db: Database, target: config.CTarget) -> dict[str, str]:
    """cantools pack/unpack for the messages this node sends or receives."""
    header, source, _, _ = generate(
        db,
        "platform",
        "platform.h",
        "platform.c",
        "platform_fuzzer.c",
        floating_point_numbers=True,
        use_float=True,  # single-precision FPU (H7/G4/ESP32-S3); no double math on MCUs
        node_name=None if target.all_messages else target.node,
    )
    source = _encode_rounding(_misra_fixups(_strip_date(source)), header)
    return {"platform.h": _strip_date(header), "platform.c": source}


# --------------------------------------------------------------------------- E2E wrappers


def generate_e2e_c(db: Database, target: config.CTarget) -> dict[str, str]:
    """Core E2E library plus per-message wrappers with DataID/timeout constants."""
    msgs = [
        m for m in sorted(db.messages, key=lambda m: m.frame_id)
        if is_e2e_protected(m, db) and (_sends(target, m) or _receives(target, m))
    ]  # fmt: skip
    src = "dbc/platform.dbc"
    h = [BANNER.format(source=src), "#ifndef PLATFORM_E2E_H", "#define PLATFORM_E2E_H", ""]
    h += ['#include "moto_e2e.h"', "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    c = [BANNER.format(source=src), '#include "platform_e2e.h"', ""]
    for m in msgs:
        snake = camel_to_snake_case(m.name)
        up = f"PLATFORM_{snake.upper()}"
        fn = f"platform_{snake}_e2e"
        cycle = cycle_time_ms(m)
        h.append(f"/* {m.name} 0x{m.frame_id:03X}, cycle {cycle} ms, sender {m.senders[0]} */")
        h.append(f"#define {up}_E2E_DATA_ID ({_hex(e2e_data_id(m, db), 4)})")
        h.append(f"#define {up}_E2E_TIMEOUT_MS ({cycle * config.E2E_TIMEOUT_CYCLES}u)")
        h.append(f"#define {up}_E2E_MAX_DELTA_COUNTER ({config.E2E_MAX_DELTA_COUNTER}u)")
        if _sends(target, m):
            h.append(
                f"moto_e2e_status_t {fn}_protect(uint8_t *data, size_t size, "
                "moto_e2e_tx_state_t *state);"
            )
            c += [
                f"moto_e2e_status_t {fn}_protect(uint8_t *data, size_t size, "
                "moto_e2e_tx_state_t *state)",
                "{",
                f"    return moto_e2e_protect({up}_E2E_DATA_ID, data, size, state);",
                "}",
                "",
            ]
        if _receives(target, m):
            h.append(
                f"moto_e2e_status_t {fn}_check(const uint8_t *data, size_t size, "
                "moto_e2e_rx_state_t *state, uint32_t now_ms);"
            )
            h.append(
                f"moto_e2e_status_t {fn}_check_timeout(moto_e2e_rx_state_t *state, "
                "uint32_t now_ms);"
            )
            c += [
                f"moto_e2e_status_t {fn}_check(const uint8_t *data, size_t size, "
                "moto_e2e_rx_state_t *state, uint32_t now_ms)",
                "{",
                f"    return moto_e2e_check({up}_E2E_DATA_ID, {up}_E2E_MAX_DELTA_COUNTER, "
                f"{up}_E2E_TIMEOUT_MS, data, size, state, now_ms);",
                "}",
                "",
                f"moto_e2e_status_t {fn}_check_timeout(moto_e2e_rx_state_t *state, "
                "uint32_t now_ms)",
                "{",
                f"    return moto_e2e_check_timeout(state, {up}_E2E_TIMEOUT_MS, now_ms);",
                "}",
                "",
            ]
        h.append("")
    h += ["#ifdef __cplusplus", "}", "#endif", "", "#endif /* PLATFORM_E2E_H */", ""]
    return {
        "moto_e2e.h": E2E_CORE_H,
        "moto_e2e.c": E2E_CORE_C,
        "platform_e2e.h": "\n".join(h),
        "platform_e2e.c": "\n".join(c).rstrip("\n") + "\n",
    }


# --------------------------------------------------------------------------- CL250 DIDs


def _hex(value: int, width: int) -> str:
    return f"0x{value:0{width}X}u"


def _c_float(value: float) -> str:
    text = repr(float(value))
    return f"{text}f"


def generate_vehicle_c(vehicle: dict[str, Any]) -> dict[str, str]:
    # Never emit an allow-list wider than D-020, whatever the YAML says.
    config.assert_policy_within_d020(vehicle["tester_policy"])
    fc_frame = config.vehicle_fc_frame(vehicle["transport"])  # raises outside D-059
    src = "uds/vehicle_cl250.yaml"
    p = "VEHICLE_CL250"
    addr = vehicle["addressing"]
    timing = vehicle["timing"]
    session = vehicle["session"]
    dids = vehicle["dids"]

    def define(name: str, value: str, comment: str = "") -> str:
        tail = f" /* {comment} */" if comment else ""
        return f"#define {p}_{name} ({value}){tail}"

    h = [BANNER.format(source=src), "#ifndef VEHICLE_CL250_H", "#define VEHICLE_CL250_H", ""]
    h += ["#include <stdbool.h>", "#include <stddef.h>", "#include <stdint.h>", ""]
    h += ["#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    h += [f"/* {vehicle['vehicle']} engine ECU, polled over UDS by the single vehicle-bus",
          " * tester (D-021). Source facts verified on the vehicle (D-019). */", ""]  # fmt: skip
    h.append(define("BITRATE", f"{vehicle['bus']['bitrate']}u"))
    h.append(define("REQUEST_ID", _hex(addr["primary"]["request_id"], 8), "29-bit"))
    h.append(define("RESPONSE_ID", _hex(addr["primary"]["response_id"], 8), "29-bit"))
    fb_note = (
        "11-bit fallback, verified"
        if addr["fallback"]["verified"]
        else "11-bit fallback, UNVERIFIED"
    )
    h.append(define("FALLBACK_REQUEST_ID", _hex(addr["fallback"]["request_id"], 3), fb_note))
    h.append(define("FALLBACK_RESPONSE_ID", _hex(addr["fallback"]["response_id"], 3), fb_note))
    watch = addr["functional_watch"]["ids"]
    h += [
        "",
        "/* Q-021/D-040: OBD functional request IDs (ISO 15765-4), WATCH-ONLY. The tester",
        " * never sends on them; a frame seen there means a second tester (D-021). */",
        define("FUNCTIONAL_WATCH_COUNT", f"{len(watch)}u"),
        "typedef struct {",
        "    uint32_t id;",
        "    bool extended; /* 29-bit */",
        "} vehicle_cl250_watch_id_t;",
        f"extern const vehicle_cl250_watch_id_t vehicle_cl250_functional_watch[{p}_FUNCTIONAL_WATCH_COUNT];",
        "",
    ]
    h.append(define("FRAME_DLC", f"{vehicle['transport']['frame_dlc']}u"))
    h.append(define("PADDING_BYTE", _hex(vehicle["transport"]["padding_byte"], 2)))
    fc = vehicle["transport"]["flow_control"]
    h += [
        "",
        "/* D-059 (Q-020): the one Flow Control frame the tester may send, FC.CTS, while it",
        " * receives the segmented answer to its own allowed request, and only for a First",
        " * Frame with FF_DL <= MAX_FF_DL (anything longer gets no FC). The frame gate passes",
        " * exactly vehicle_cl250_fc_cts[], byte for byte. */",
        define("FC_BLOCK_SIZE", f"{fc['block_size']}u", "one FC per reception"),
        define("FC_ST_MIN_MS", f"{fc['st_min_ms']}u"),
        define("MAX_FF_DL", f"{fc['max_ff_dl']}u", "bytes"),
        f"extern const uint8_t vehicle_cl250_fc_cts[{p}_FRAME_DLC];",
        "",
    ]
    start = session["start"]
    tp = session["tester_present"]
    h.append(define("SESSION_SID", _hex(start["request"][0], 2)))
    h.append(define("SESSION_SUBFUNCTION", _hex(start["request"][1], 2), "extended session"))
    h.append(define("SESSION_POSITIVE_SID", _hex(start["positive_response_sid"], 2)))
    h.append(define("SESSION_RETRY_INTERVAL_MS", f"{start['retry_interval_ms']}u"))
    h.append(define("TESTER_PRESENT_SID", _hex(tp["request"][0], 2)))
    h.append(define("TESTER_PRESENT_SUBFUNCTION", _hex(tp["request"][1], 2), "suppress response"))
    h.append(define("TESTER_PRESENT_PERIOD_MS", f"{tp['period_ms']}u"))
    h.append("")
    for key in sorted(timing):
        if key in ("verified", "evidence"):
            continue
        h.append(define(key.upper(), f"{timing[key]}u"))
    h.append("")
    h.append(define("DID_COUNT", f"{len(dids)}u"))
    for d in dids:
        h.append(define(f"DID_{d['name']}", _hex(d["did"], 4), d["formula"]))
    h.append("")
    h += [
        "/* D-043 poll priority classes (vehicle_cl250_did_t.priority). A due DID of a",
        " * lower value is served first; within a class, table order. Priority changes",
        " * the order only: every due DID is still served within its stale_after_ms.",
        " * Plain constants, not an enum: the field is uint8_t (no unused type, MISRA 2.3). */",
    ]
    for i, prio in enumerate(DID_PRIORITIES):
        h.append(define(f"PRIORITY_{prio.upper()}", f"{i}u"))
    h.append("")
    h.append("/* Index into vehicle_cl250_dids[] (table order, not the poll priority). */")
    h.append("typedef enum {")
    for i, d in enumerate(dids):
        h.append(f"    {p}_IDX_{d['name']} = {i},")
    h.append("} vehicle_cl250_did_index_t;")
    h.append("")
    h += [
        "/* physical = raw * factor_num / factor_den + offset,",
        " * raw = `length` data bytes after the DID echo, unsigned big-endian. */",
        "typedef struct {",
        "    uint16_t did;",
        "    uint8_t length;",
        "    uint8_t priority; /* VEHICLE_CL250_PRIORITY_* (D-043) */",
        "    uint16_t poll_period_ms;",
        "    uint16_t stale_after_ms; /* value older than this must not be used/republished */",
        "    int32_t factor_num;",
        "    int32_t factor_den;",
        "    int32_t offset;",
        "    float min;",
        "    float max;",
        "    bool verified;",
        "} vehicle_cl250_did_t;",
        "",
        f"extern const vehicle_cl250_did_t vehicle_cl250_dids[{p}_DID_COUNT];",
        "",
        "/* Returns the table entry for `did`, or NULL. */",
        "const vehicle_cl250_did_t *vehicle_cl250_find(uint16_t did);",
        "",
        "/* Decodes `length` bytes (big-endian) to the physical value. Returns false if",
        " * data is NULL, too short, or the result is outside [min, max]. */",
        "bool vehicle_cl250_decode(const vehicle_cl250_did_t *entry, const uint8_t *data,",
        "                          size_t size, float *out);",
        "",
        "/* D-020 allow-list. `payload` is the UDS/OBD request starting with the SID",
        " * (no ISO-TP PCI). Returns true only for services the tester may send.",
        " * Every vehicle-bus transmission must pass this check. */",
        "bool vehicle_cl250_request_allowed(const uint8_t *payload, size_t size);",
        "",
        "/* Last gate before the CAN driver: `frame` is the raw ISO-TP frame. Accepted:",
        " * a Single Frame (PCI 0x01..0x07) whose payload passes",
        " * vehicle_cl250_request_allowed(), or (D-059) exactly the 8-byte",
        " * vehicle_cl250_fc_cts[]. Refused: FF/CF (requests are never multi-frame) and",
        " * any other FC. Stateless: when an FC may be sent is the client's job. */",
        "bool vehicle_cl250_frame_allowed(const uint8_t *frame, size_t size);",
        "",
        "/* D-059 discovery scan, run once by conn's probe env, in table order. Standard",
        " * requests (SAE J1979, ISO 14229-1), each checked against the gates by codegen.",
        " * bitmap_offset != 0: the positive response carries a 4-byte support bitmap at",
        " * this offset (counted from the response SID); bit 7 of its first byte is id",
        " * base + 1, base = the last request byte. after != SCAN_NONE: send only if entry",
        " * `after`'s bitmap marks `after_id` supported. */",
        define("SCAN_COUNT", f"{len(vehicle['discovery_scan']['requests'])}u"),
        define("SCAN_REQUEST_MAX", f"{SCAN_REQUEST_MAX}u", "request bytes"),
        define("SCAN_NONE", "0xFFu", "no `after` condition"),
        "typedef struct {",
        f"    uint8_t request[{p}_SCAN_REQUEST_MAX];",
        "    uint8_t size;          /* request bytes used */",
        "    uint8_t bitmap_offset; /* 0 = the answer is not a support bitmap */",
        "    uint8_t after;         /* index of the gating bitmap entry, or SCAN_NONE */",
        "    uint8_t after_id;      /* id that entry must mark supported */",
        "} vehicle_cl250_scan_t;",
        f"extern const vehicle_cl250_scan_t vehicle_cl250_discovery_scan[{p}_SCAN_COUNT];",
        "",
        "/* Parses a raw ReadDataByIdentifier response frame for `expected_did`:",
        " * checks Single Frame PCI, SID 0x62, the DID echo and the length, then",
        " * decodes. Returns false for anything else (NRC, other DID, FF, short). */",
        "bool vehicle_cl250_parse_response(uint16_t expected_did, const uint8_t *frame,",
        "                                  size_t size, float *out);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* VEHICLE_CL250_H */",
        "",
    ]

    c = [BANNER.format(source=src), '#include "vehicle_cl250.h"', ""]
    c.append(
        f"const vehicle_cl250_watch_id_t vehicle_cl250_functional_watch[{p}_FUNCTIONAL_WATCH_COUNT] = {{"
    )
    for w in watch:
        ext = w["id_type"] == "extended_29bit"
        c.append(f"    {{ {_hex(w['id'], 8 if ext else 3)}, {'true' if ext else 'false'} }},")
    c += ["};", ""]
    c.append(f"const uint8_t vehicle_cl250_fc_cts[{p}_FRAME_DLC] = {{")
    c.append("    " + ", ".join(_hex(b, 2) for b in fc_frame))
    c += ["};", ""]
    entries = vehicle["discovery_scan"]["requests"]
    index = {e["name"]: i for i, e in enumerate(entries)}
    c.append(f"const vehicle_cl250_scan_t vehicle_cl250_discovery_scan[{p}_SCAN_COUNT] = {{")
    for e in entries:
        req = e["request"] + [0] * (SCAN_REQUEST_MAX - len(e["request"]))
        after = e.get("after")
        after_index = f"{index[after['name']]}u" if after else f"{p}_SCAN_NONE"
        after_id = _hex(after["id"], 2) if after else "0x00u"
        bitmap_offset = len(e["request"]) if e.get("bitmap") else 0
        c.append(
            "    { { " + ", ".join(_hex(b, 2) for b in req) + " }, "
            f"{len(e['request'])}u, {bitmap_offset}u, {after_index}, {after_id} }}, "
            f"/* {e['name']} */"
        )
    c += ["};", ""]
    c.append(f"const vehicle_cl250_did_t vehicle_cl250_dids[{p}_DID_COUNT] = {{")
    for d in dids:
        c.append(
            f"    {{ {p}_DID_{d['name']}, {d['length']}u, "
            f"{p}_PRIORITY_{d['priority'].upper()}, "
            f"{d['poll_period_ms']}u, {d['stale_after_ms']}u, "
            f"{d['factor_num']}, {d['factor_den']}, {d['offset']}, "
            f"{_c_float(d['min'])}, {_c_float(d['max'])}, {'true' if d['verified'] else 'false'} }},"
        )
    c += ["};", ""]
    c += [
        "const vehicle_cl250_did_t *vehicle_cl250_find(uint16_t did)",
        "{",
        "    const vehicle_cl250_did_t *found = NULL;",
        "    size_t i;",
        "",
        f"    for (i = 0u; i < {p}_DID_COUNT; i++) {{",
        "        if ((found == NULL) && (vehicle_cl250_dids[i].did == did)) {",
        "            found = &vehicle_cl250_dids[i];",
        "        }",
        "    }",
        "    return found;",
        "}",
        "",
        "bool vehicle_cl250_decode(const vehicle_cl250_did_t *entry, const uint8_t *data,",
        "                          size_t size, float *out)",
        "{",
        "    bool ok = false; /* fail-closed default */",
        "",
        "    if ((entry == NULL) || (data == NULL) || (out == NULL) || (size < entry->length) ||",
        "        (entry->length == 0u) || (entry->length > 4u) || (entry->factor_den == 0)) {",
        "        ok = false;",
        "    } else {",
        "        uint32_t raw = 0u;",
        "        float value;",
        "        size_t i;",
        "",
        "        for (i = 0u; i < entry->length; i++) {",
        "            raw = (raw << 8u) | (uint32_t)data[i];",
        "        }",
        "        value = ((float)raw * (float)entry->factor_num) / (float)entry->factor_den;",
        "        value += (float)entry->offset;",
        "        if ((value < entry->min) || (value > entry->max)) {",
        "            ok = false;",
        "        } else {",
        "            *out = value;",
        "            ok = true;",
        "        }",
        "    }",
        "    return ok;",
        "}",
        "",
        "bool vehicle_cl250_request_allowed(const uint8_t *payload, size_t size)",
        "{",
        "    bool ok = false; /* fail-closed default */",
        "",
        "    if ((payload == NULL) || (size == 0u)) {",
        "        ok = false;",
        "    } else {",
        "        switch (payload[0]) {",
    ]
    forbidden_subs = config.FORBIDDEN_VEHICLE_SUBFUNCTIONS
    for entry in vehicle["tester_policy"]["allowed"]:
        sid = entry["sid"]
        c.append(f"        case {_hex(sid, 2)}: /* {entry['name']} */")
        subs = entry.get("subfunctions")
        if subs is None:
            c += ["            ok = true;", "            break;"]
            continue
        allowed = [s for s in subs if s not in forbidden_subs.get(sid, ())]
        if not allowed:  # a narrowed policy: the service stays listed, nothing passes
            c += ["            ok = false; /* no sub-function allowed */", "            break;"]
            continue
        cond = " || ".join(f"(sub == {_hex(s, 2)})" for s in allowed)
        c += [
            "            if (size < 2u) {",
            "                ok = false;",
            "            } else {",
            "                uint8_t sub = (uint8_t)(payload[1] & 0x7Fu); /* ignore suppressPosRsp bit */",
            "",
            f"                ok = {cond};",
            "            }",
            "            break;",
        ]
    c += [
        "        default:",
        "            ok = false; /* includes every D-020 forbidden service */",
        "            break;",
        "        }",
        "    }",
        "    return ok;",
        "}",
        "",
        "bool vehicle_cl250_frame_allowed(const uint8_t *frame, size_t size)",
        "{",
        "    bool ok = false; /* fail-closed default */",
        "",
        "    if ((frame == NULL) || (size < 2u)) {",
        "        ok = false;",
        "    } else if ((frame[0] & 0xF0u) == 0u) { /* Single Frame request */",
        "        size_t len = (size_t)(frame[0] & 0x0Fu);",
        "",
        "        if ((len == 0u) || (len > 7u) || ((len + 1u) > size)) {",
        "            ok = false;",
        "        } else {",
        "            ok = vehicle_cl250_request_allowed(&frame[1], len);",
        "        }",
        f"    }} else if (size == {p}_FRAME_DLC) {{ /* D-059: only the one FC.CTS, byte for byte */",
        "        size_t i;",
        "",
        "        ok = true;",
        f"        for (i = 0u; i < {p}_FRAME_DLC; i++) {{",
        "            if (frame[i] != vehicle_cl250_fc_cts[i]) {",
        "                ok = false;",
        "            }",
        "        }",
        "    } else {",
        "        ok = false; /* FF, CF, any other FC or size */",
        "    }",
        "    return ok;",
        "}",
        "",
        "bool vehicle_cl250_parse_response(uint16_t expected_did, const uint8_t *frame,",
        "                                  size_t size, float *out)",
        "{",
        "    const vehicle_cl250_did_t *entry = vehicle_cl250_find(expected_did);",
        "    bool ok = false; /* fail-closed default */",
        "",
        "    if ((entry == NULL) || (frame == NULL) || (out == NULL) || (size < 1u) ||",
        "        ((frame[0] & 0xF0u) != 0u)) {",
        "        ok = false;",
        "    } else {",
        "        size_t len = (size_t)(frame[0] & 0x0Fu);",
        "",
        "        if ((len > 7u) || ((len + 1u) > size) || (len < (3u + (size_t)entry->length))) {",
        "            ok = false;",
        "        } else if ((frame[1] != 0x62u) || (frame[2] != (uint8_t)(expected_did >> 8u)) ||",
        "                   (frame[3] != (uint8_t)(expected_did & 0xFFu))) {",
        "            ok = false;",
        "        } else {",
        "            ok = vehicle_cl250_decode(entry, &frame[4], len - 3u, out);",
        "        }",
        "    }",
        "    return ok;",
        "}",
        "",
    ]
    return {"vehicle_cl250.h": "\n".join(h), "vehicle_cl250.c": "\n".join(c)}


# --------------------------------------------------------------------------- limits


def generate_limits_c(limits: dict[str, Any], node: str) -> dict[str, str]:
    """Shared cornering/speed limits (D-029), only the sections in `node`'s scope.

    Values only; the rules live in the YAML."""
    h = [BANNER.format(source="limits/platform_limits.yaml"), "#ifndef PLATFORM_LIMITS_H"]
    h += ["#define PLATFORM_LIMITS_H", "", "#include <stdbool.h>", "#include <stdint.h>", ""]
    h += ["/* Provisional values are revisited with measured data; each value's rule is in",
          " * limits/platform_limits.yaml. */"]  # fmt: skip
    for section in limit_scope(limits, node):
        for key, entry in limits[section].items():
            if entry["value"] is None:
                h.append(f"/* {key}: none by design ({entry['status']}), see the YAML rule. */")
                continue
            name = f"PLATFORM_LIMIT_{key.upper()}"
            val = entry["value"]
            text = f"{val}u" if isinstance(val, int) and key.endswith("_ms") else _c_float(val)
            h.append(f"#define {name} ({text}) /* {entry['status']} */")
    h += [
        "",
        "/* EKF estimate states (*_STATE): only ESTIMATED (0) and CLAMPED (1) are usable.",
        " * DEFAULT (2) follows the per-value rule; INVALID (3), RESERVED and any unknown",
        " * value are never usable. Allow-list on purpose: new states default to unusable. */",
        "static inline bool platform_estimate_state_usable(uint8_t state)",
        "{",
        "    return (state == 0u) || (state == 1u);",
        "}",
        "",
        "#endif /* PLATFORM_LIMITS_H */",
        "",
    ]
    return {"platform_limits.h": "\n".join(h)}
