"""C code generation: per-node cantools pack/unpack, E2E and the CL250 DID table.

All generated C is C99, uses only fixed-width types, no dynamic memory, no
recursion and no string/DBC parsing (platform invariant 5).
"""

from __future__ import annotations

import re
from typing import Any

from cantools.database.can import Database, Message
from cantools.database.can.c_source import camel_to_snake_case, generate

from . import config
from .c_e2e_templates import BANNER, E2E_CORE_C, E2E_CORE_H
from .dbc_checks import cycle_time_ms, e2e_data_id, is_e2e_protected

_CANTOOLS_DATE_RE = re.compile(r"(generated by cantools version \S+) .*?\.$", re.MULTILINE)


def _strip_date(text: str) -> str:
    """cantools stamps the generation time; drop it so `make gen` is reproducible."""
    return _CANTOOLS_DATE_RE.sub(r"\1.", text)


def _sends(target: config.CTarget, msg: Message) -> bool:
    return target.all_messages or target.node in msg.senders


def _receives(target: config.CTarget, msg: Message) -> bool:
    return target.all_messages or target.node in msg.receivers


def generate_platform_c(db: Database, target: config.CTarget) -> dict[str, str]:
    """cantools pack/unpack for the messages this node sends or receives."""
    header, source, _, _ = generate(
        db,
        "platform",
        "platform.h",
        "platform.c",
        "platform_fuzzer.c",
        floating_point_numbers=True,
        use_float=True,  # single-precision FPU (H7/G4/ESP32-S3); no double math on MCUs
        node_name=None if target.all_messages else target.node,
    )
    return {"platform.h": _strip_date(header), "platform.c": _strip_date(source)}


# --------------------------------------------------------------------------- E2E wrappers


def generate_e2e_c(db: Database, target: config.CTarget) -> dict[str, str]:
    """Core E2E library plus per-message wrappers with DataID/timeout constants."""
    msgs = [
        m for m in sorted(db.messages, key=lambda m: m.frame_id)
        if is_e2e_protected(m, db) and (_sends(target, m) or _receives(target, m))
    ]  # fmt: skip
    src = "dbc/platform.dbc"
    h = [BANNER.format(source=src), "#ifndef PLATFORM_E2E_H", "#define PLATFORM_E2E_H", ""]
    h += ['#include "moto_e2e.h"', "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    c = [BANNER.format(source=src), '#include "platform_e2e.h"', ""]
    for m in msgs:
        snake = camel_to_snake_case(m.name)
        up = f"PLATFORM_{snake.upper()}"
        fn = f"platform_{snake}_e2e"
        cycle = cycle_time_ms(m)
        h.append(f"/* {m.name} 0x{m.frame_id:03X}, cycle {cycle} ms, sender {m.senders[0]} */")
        h.append(f"#define {up}_E2E_DATA_ID ({_hex(e2e_data_id(m, db), 4)})")
        h.append(f"#define {up}_E2E_TIMEOUT_MS ({cycle * config.E2E_TIMEOUT_CYCLES}u)")
        h.append(f"#define {up}_E2E_MAX_DELTA_COUNTER ({config.E2E_MAX_DELTA_COUNTER}u)")
        if _sends(target, m):
            h.append(
                f"moto_e2e_status_t {fn}_protect(uint8_t *data, size_t size, "
                "moto_e2e_tx_state_t *state);"
            )
            c += [
                f"moto_e2e_status_t {fn}_protect(uint8_t *data, size_t size, "
                "moto_e2e_tx_state_t *state)",
                "{",
                f"    return moto_e2e_protect({up}_E2E_DATA_ID, data, size, state);",
                "}",
                "",
            ]
        if _receives(target, m):
            h.append(
                f"moto_e2e_status_t {fn}_check(const uint8_t *data, size_t size, "
                "moto_e2e_rx_state_t *state, uint32_t now_ms);"
            )
            h.append(
                f"moto_e2e_status_t {fn}_check_timeout(moto_e2e_rx_state_t *state, "
                "uint32_t now_ms);"
            )
            c += [
                f"moto_e2e_status_t {fn}_check(const uint8_t *data, size_t size, "
                "moto_e2e_rx_state_t *state, uint32_t now_ms)",
                "{",
                f"    return moto_e2e_check({up}_E2E_DATA_ID, {up}_E2E_MAX_DELTA_COUNTER, "
                f"{up}_E2E_TIMEOUT_MS, data, size, state, now_ms);",
                "}",
                "",
                f"moto_e2e_status_t {fn}_check_timeout(moto_e2e_rx_state_t *state, "
                "uint32_t now_ms)",
                "{",
                f"    return moto_e2e_check_timeout(state, {up}_E2E_TIMEOUT_MS, now_ms);",
                "}",
                "",
            ]
        h.append("")
    h += ["#ifdef __cplusplus", "}", "#endif", "", "#endif /* PLATFORM_E2E_H */", ""]
    return {
        "moto_e2e.h": E2E_CORE_H,
        "moto_e2e.c": E2E_CORE_C,
        "platform_e2e.h": "\n".join(h),
        "platform_e2e.c": "\n".join(c).rstrip("\n") + "\n",
    }


# --------------------------------------------------------------------------- CL250 DIDs


def _hex(value: int, width: int) -> str:
    return f"0x{value:0{width}X}u"


def _c_float(value: float) -> str:
    text = repr(float(value))
    return f"{text}f"


def generate_vehicle_c(vehicle: dict[str, Any]) -> dict[str, str]:
    # Never emit an allow-list wider than D-020, whatever the YAML says.
    config.assert_policy_within_d020(vehicle["tester_policy"])
    src = "uds/vehicle_cl250.yaml"
    p = "VEHICLE_CL250"
    addr = vehicle["addressing"]
    timing = vehicle["timing"]
    session = vehicle["session"]
    dids = vehicle["dids"]

    def define(name: str, value: str, comment: str = "") -> str:
        tail = f" /* {comment} */" if comment else ""
        return f"#define {p}_{name} ({value}){tail}"

    h = [BANNER.format(source=src), "#ifndef VEHICLE_CL250_H", "#define VEHICLE_CL250_H", ""]
    h += ["#include <stdbool.h>", "#include <stddef.h>", "#include <stdint.h>", ""]
    h += ["#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    h += [f"/* {vehicle['vehicle']} engine ECU, polled over UDS by the single vehicle-bus",
          " * tester (D-021). Source facts verified on the vehicle (D-019). */", ""]  # fmt: skip
    h.append(define("BITRATE", f"{vehicle['bus']['bitrate']}u"))
    h.append(define("REQUEST_ID", _hex(addr["primary"]["request_id"], 8), "29-bit"))
    h.append(define("RESPONSE_ID", _hex(addr["primary"]["response_id"], 8), "29-bit"))
    fb_note = (
        "11-bit fallback, verified"
        if addr["fallback"]["verified"]
        else "11-bit fallback, UNVERIFIED"
    )
    h.append(define("FALLBACK_REQUEST_ID", _hex(addr["fallback"]["request_id"], 3), fb_note))
    h.append(define("FALLBACK_RESPONSE_ID", _hex(addr["fallback"]["response_id"], 3), fb_note))
    watch = addr["functional_watch"]["ids"]
    h += [
        "",
        "/* Q-021/D-040: OBD functional request IDs (ISO 15765-4), WATCH-ONLY. The tester",
        " * never sends on them; a frame seen there means a second tester (D-021). */",
        define("FUNCTIONAL_WATCH_COUNT", f"{len(watch)}u"),
        "typedef struct {",
        "    uint32_t id;",
        "    bool extended; /* 29-bit */",
        "} vehicle_cl250_watch_id_t;",
        f"extern const vehicle_cl250_watch_id_t vehicle_cl250_functional_watch[{p}_FUNCTIONAL_WATCH_COUNT];",
        "",
    ]
    h.append(define("FRAME_DLC", f"{vehicle['transport']['frame_dlc']}u"))
    h.append(define("PADDING_BYTE", _hex(vehicle["transport"]["padding_byte"], 2)))
    h.append("")
    start = session["start"]
    tp = session["tester_present"]
    h.append(define("SESSION_SID", _hex(start["request"][0], 2)))
    h.append(define("SESSION_SUBFUNCTION", _hex(start["request"][1], 2), "extended session"))
    h.append(define("SESSION_POSITIVE_SID", _hex(start["positive_response_sid"], 2)))
    h.append(define("SESSION_RETRY_INTERVAL_MS", f"{start['retry_interval_ms']}u"))
    h.append(define("TESTER_PRESENT_SID", _hex(tp["request"][0], 2)))
    h.append(define("TESTER_PRESENT_SUBFUNCTION", _hex(tp["request"][1], 2), "suppress response"))
    h.append(define("TESTER_PRESENT_PERIOD_MS", f"{tp['period_ms']}u"))
    h.append("")
    for key in sorted(timing):
        if key in ("verified", "evidence"):
            continue
        h.append(define(key.upper(), f"{timing[key]}u"))
    h.append("")
    h.append(define("DID_COUNT", f"{len(dids)}u"))
    for d in dids:
        h.append(define(f"DID_{d['name']}", _hex(d["did"], 4), d["formula"]))
    h.append("")
    h.append("/* Index into vehicle_cl250_dids[] (poll priority order). */")
    h.append("typedef enum {")
    for i, d in enumerate(dids):
        h.append(f"    {p}_IDX_{d['name']} = {i},")
    h.append("} vehicle_cl250_did_index_t;")
    h.append("")
    h += [
        "/* physical = raw * factor_num / factor_den + offset,",
        " * raw = `length` data bytes after the DID echo, unsigned big-endian. */",
        "typedef struct {",
        "    uint16_t did;",
        "    uint8_t length;",
        "    uint16_t poll_period_ms;",
        "    uint16_t stale_after_ms; /* value older than this must not be used/republished */",
        "    int32_t factor_num;",
        "    int32_t factor_den;",
        "    int32_t offset;",
        "    float min;",
        "    float max;",
        "    bool verified;",
        "} vehicle_cl250_did_t;",
        "",
        f"extern const vehicle_cl250_did_t vehicle_cl250_dids[{p}_DID_COUNT];",
        "",
        "/* Returns the table entry for `did`, or NULL. */",
        "const vehicle_cl250_did_t *vehicle_cl250_find(uint16_t did);",
        "",
        "/* Decodes `length` bytes (big-endian) to the physical value. Returns false if",
        " * data is NULL, too short, or the result is outside [min, max]. */",
        "bool vehicle_cl250_decode(const vehicle_cl250_did_t *entry, const uint8_t *data,",
        "                          size_t size, float *out);",
        "",
        "/* D-020 allow-list. `payload` is the UDS/OBD request starting with the SID",
        " * (no ISO-TP PCI). Returns true only for services the tester may send.",
        " * Every vehicle-bus transmission must pass this check. */",
        "bool vehicle_cl250_request_allowed(const uint8_t *payload, size_t size);",
        "",
        "/* Last gate before the CAN driver: `frame` is the raw ISO-TP frame. Only a",
        " * Single Frame (PCI 0x01..0x07) whose payload passes",
        " * vehicle_cl250_request_allowed() is accepted; FF/CF/FC are refused (the",
        " * tester never needs multi-frame requests). */",
        "bool vehicle_cl250_frame_allowed(const uint8_t *frame, size_t size);",
        "",
        "/* Parses a raw ReadDataByIdentifier response frame for `expected_did`:",
        " * checks Single Frame PCI, SID 0x62, the DID echo and the length, then",
        " * decodes. Returns false for anything else (NRC, other DID, FF, short). */",
        "bool vehicle_cl250_parse_response(uint16_t expected_did, const uint8_t *frame,",
        "                                  size_t size, float *out);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* VEHICLE_CL250_H */",
        "",
    ]

    c = [BANNER.format(source=src), '#include "vehicle_cl250.h"', ""]
    c.append(
        f"const vehicle_cl250_watch_id_t vehicle_cl250_functional_watch[{p}_FUNCTIONAL_WATCH_COUNT] = {{"
    )
    for w in watch:
        ext = w["id_type"] == "extended_29bit"
        c.append(f"    {{ {_hex(w['id'], 8 if ext else 3)}, {'true' if ext else 'false'} }},")
    c += ["};", ""]
    c.append(f"const vehicle_cl250_did_t vehicle_cl250_dids[{p}_DID_COUNT] = {{")
    for d in dids:
        c.append(
            f"    {{ {p}_DID_{d['name']}, {d['length']}u, {d['poll_period_ms']}u, {d['stale_after_ms']}u, "
            f"{d['factor_num']}, {d['factor_den']}, {d['offset']}, "
            f"{_c_float(d['min'])}, {_c_float(d['max'])}, {'true' if d['verified'] else 'false'} }},"
        )
    c += ["};", ""]
    c += [
        "const vehicle_cl250_did_t *vehicle_cl250_find(uint16_t did)",
        "{",
        "    size_t i;",
        "",
        f"    for (i = 0u; i < {p}_DID_COUNT; i++) {{",
        "        if (vehicle_cl250_dids[i].did == did) {",
        "            return &vehicle_cl250_dids[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
        "bool vehicle_cl250_decode(const vehicle_cl250_did_t *entry, const uint8_t *data,",
        "                          size_t size, float *out)",
        "{",
        "    uint32_t raw = 0u;",
        "    float value;",
        "    size_t i;",
        "",
        "    if ((entry == NULL) || (data == NULL) || (out == NULL) || (size < entry->length) ||",
        "        (entry->length == 0u) || (entry->length > 4u) || (entry->factor_den == 0)) {",
        "        return false;",
        "    }",
        "    for (i = 0u; i < entry->length; i++) {",
        "        raw = (raw << 8u) | (uint32_t)data[i];",
        "    }",
        "    value = ((float)raw * (float)entry->factor_num) / (float)entry->factor_den;",
        "    value += (float)entry->offset;",
        "    if ((value < entry->min) || (value > entry->max)) {",
        "        return false;",
        "    }",
        "    *out = value;",
        "    return true;",
        "}",
        "",
        "bool vehicle_cl250_request_allowed(const uint8_t *payload, size_t size)",
        "{",
        "    uint8_t sub;",
        "",
        "    if ((payload == NULL) || (size == 0u)) {",
        "        return false;",
        "    }",
        "    switch (payload[0]) {",
    ]
    forbidden_subs = config.FORBIDDEN_VEHICLE_SUBFUNCTIONS
    for entry in vehicle["tester_policy"]["allowed"]:
        sid = entry["sid"]
        c.append(f"    case {_hex(sid, 2)}: /* {entry['name']} */")
        subs = entry.get("subfunctions")
        if subs is None:
            c.append("        return true;")
            continue
        allowed = [s for s in subs if s not in forbidden_subs.get(sid, ())]
        cond = " || ".join(f"(sub == {_hex(s, 2)})" for s in allowed) or "false"
        c += [
            "        if (size < 2u) {",
            "            return false;",
            "        }",
            "        sub = (uint8_t)(payload[1] & 0x7Fu); /* ignore suppressPosRsp bit */",
            f"        return {cond};",
        ]
    c += [
        "    default:",
        "        return false; /* includes every D-020 forbidden service */",
        "    }",
        "}",
        "",
        "bool vehicle_cl250_frame_allowed(const uint8_t *frame, size_t size)",
        "{",
        "    size_t len;",
        "",
        "    if ((frame == NULL) || (size < 2u) || ((frame[0] & 0xF0u) != 0u)) {",
        "        return false; /* not a Single Frame */",
        "    }",
        "    len = (size_t)(frame[0] & 0x0Fu);",
        "    if ((len == 0u) || (len > 7u) || ((len + 1u) > size)) {",
        "        return false;",
        "    }",
        "    return vehicle_cl250_request_allowed(&frame[1], len);",
        "}",
        "",
        "bool vehicle_cl250_parse_response(uint16_t expected_did, const uint8_t *frame,",
        "                                  size_t size, float *out)",
        "{",
        "    const vehicle_cl250_did_t *entry = vehicle_cl250_find(expected_did);",
        "    size_t len;",
        "",
        "    if ((entry == NULL) || (frame == NULL) || (out == NULL) || (size < 1u) ||",
        "        ((frame[0] & 0xF0u) != 0u)) {",
        "        return false;",
        "    }",
        "    len = (size_t)(frame[0] & 0x0Fu);",
        "    if ((len > 7u) || ((len + 1u) > size) || (len < (3u + (size_t)entry->length))) {",
        "        return false;",
        "    }",
        "    if ((frame[1] != 0x62u) || (frame[2] != (uint8_t)(expected_did >> 8u)) ||",
        "        (frame[3] != (uint8_t)(expected_did & 0xFFu))) {",
        "        return false;",
        "    }",
        "    return vehicle_cl250_decode(entry, &frame[4], len - 3u, out);",
        "}",
        "",
    ]
    return {"vehicle_cl250.h": "\n".join(h), "vehicle_cl250.c": "\n".join(c)}


# --------------------------------------------------------------------------- limits


def generate_limits_c(limits: dict[str, Any]) -> dict[str, str]:
    """Shared cornering/speed limits (D-029). Values only; the rules live in the YAML."""
    h = [BANNER.format(source="limits/platform_limits.yaml"), "#ifndef PLATFORM_LIMITS_H"]
    h += ["#define PLATFORM_LIMITS_H", "", "#include <stdbool.h>", "#include <stdint.h>", ""]
    h += ["/* Provisional values are revisited with measured data; each value's rule is in",
          " * limits/platform_limits.yaml. */"]  # fmt: skip
    for section in ("cornering", "vehicle_speed"):
        for key, entry in limits[section].items():
            if entry["value"] is None:
                h.append(f"/* {key}: none by design ({entry['status']}), see the YAML rule. */")
                continue
            name = f"PLATFORM_LIMIT_{key.upper()}"
            val = entry["value"]
            text = f"{val}u" if isinstance(val, int) and key.endswith("_ms") else _c_float(val)
            h.append(f"#define {name} ({text}) /* {entry['status']} */")
    h += [
        "",
        "/* EKF estimate states (*_STATE): only ESTIMATED (0) and CLAMPED (1) are usable.",
        " * DEFAULT (2) follows the per-value rule; INVALID (3), RESERVED and any unknown",
        " * value are never usable. Allow-list on purpose: new states default to unusable. */",
        "static inline bool platform_estimate_state_usable(uint8_t state)",
        "{",
        "    return (state == 0u) || (state == 1u);",
        "}",
        "",
        "#endif /* PLATFORM_LIMITS_H */",
        "",
    ]
    return {"platform_limits.h": "\n".join(h)}
