"""Python output: gen/python/moto_defs/ (constants for host, server and HIL tools)."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat
from typing import Any

from .sources import NODE_IDS, Sources, is_e2e, msg_attr
from .templates import E2E_PY

BANNER = '"""GENERATED by moto-codegen from moto-vehicle-defs ({src}). Do not edit."""\n\n'


def _platform(src: Sources) -> str:
    messages: dict[str, dict[str, Any]] = {}
    for m in sorted(src.platform.messages, key=lambda m: m.frame_id):
        messages[m.name] = {
            "frame_id": m.frame_id,
            "length": m.length,
            "sender": m.senders[0],
            "cycle_ms": msg_attr(m, "GenMsgCycleTime", 0),
            "e2e": is_e2e(m),
            "e2e_data_id": msg_attr(m, "E2E_DataID", 0) if is_e2e(m) else None,
            "signals": [s.name for s in m.signals],
        }
    body = [
        BANNER.format(src="dbc/platform.dbc"),
        "# Decode frames with cantools and dbc/platform.dbc; these are the stable constants.\n",
        f"NODE_IDS = {pformat(NODE_IDS, sort_dicts=False)}\n",
        "E2E_TIMEOUT_CYCLES = 3\n",
        f"MESSAGES = {pformat(messages, sort_dicts=False, width=96)}\n",
        "FRAME_IDS = {name: m['frame_id'] for name, m in MESSAGES.items()}\n",
    ]
    return "\n".join(body)


def _vehicle(src: Sources) -> str:
    v = src.vehicle
    services = {
        s["sid"]: {"subfunctions": s.get("subfunctions"), "min_length": s["min_length"]}
        for s in v["allowed_services"]
    }
    dids = [
        {
            k: d[k]
            for k in (
                "name",
                "did",
                "length",
                "factor_num",
                "factor_den",
                "offset",
                "unit",
                "min",
                "max",
                "poll_period_ms",
                "verified",
            )
        }
        for d in v["dids"]
    ]
    body = [
        BANNER.format(src="uds/vehicle_cl250.yaml"),
        f"BUS = {pformat(v['bus'], sort_dicts=False)}\n",
        f"ADDRESSING = {pformat(v['addressing'], sort_dicts=False)}\n",
        "# D-020: SID -> allowed sub-functions (None = any) and minimum request length.",
        f"ALLOWED_SERVICES = {pformat(services, sort_dicts=False)}\n",
        f"SESSION = {pformat(v['session'], sort_dicts=False)}\n",
        f"TIMING = {pformat(v['timing'], sort_dicts=False)}\n",
        f"DIDS = {pformat(dids, sort_dicts=False, width=96)}\n",
        "DIDS_BY_ID = {d['did']: d for d in DIDS}\n",
        f"NRC = {pformat(v['nrc'], sort_dicts=False)}\n",
        "",
        "def decode(did: int, data: bytes) -> float:",
        '    """Physical value of a DID from the data bytes after the echoed DID."""',
        "    d = DIDS_BY_ID[did]",
        "    if len(data) < d['length']:",
        "        raise ValueError(f'DID 0x{did:04X} needs {d[\"length\"]} bytes, got {len(data)}')",
        "    raw = int.from_bytes(data[: d['length']], 'big')",
        "    return raw * d['factor_num'] / d['factor_den'] + d['offset']",
        "",
        "",
        "def _request_allowed(request: bytes) -> bool:",
        '    """D-020 rule for a UDS request (SID first); use frame_allowed() for frames."""',
        "    if not request or request[0] not in ALLOWED_SERVICES:",
        "        return False",
        "    svc = ALLOWED_SERVICES[request[0]]",
        "    if len(request) < svc['min_length']:",
        "        return False",
        "    return svc['subfunctions'] is None or request[1] in svc['subfunctions']",
        "",
        "",
        "def frame_allowed(can_id: int, is_extended: bool, frame: bytes) -> bool:",
        '    """D-020/D-021 guard for a complete CAN frame (see vehicle_cl250_frame_allowed)."""',
        "    ids = {",
        "        (a['request_id'], a['id_type'] == 'extended') for a in ADDRESSING.values()",
        "    }",
        "    if (can_id, is_extended) not in ids or not 2 <= len(frame) <= 8 or frame[0] & 0xF0:",
        "        return False",
        "    sf_len = frame[0] & 0x0F",
        "    if not 1 <= sf_len <= min(7, len(frame) - 1):",
        "        return False",
        "    return _request_allowed(bytes(frame[1 : 1 + sf_len]))",
    ]
    return "\n".join(body) + "\n"


def generate(src: Sources, out_dir: Path) -> dict[Path, str]:
    base = out_dir / "python" / "moto_defs"
    return {
        base / "__init__.py": BANNER.format(src="moto-vehicle-defs"),
        base / "platform.py": _platform(src),
        base / "vehicle_cl250.py": _vehicle(src),
        base / "e2e.py": BANNER.format(src="docs/ARCHITECTURE.md section 4") + E2E_PY,
    }
