"""Python constants for host tools (hil-bench host, server, ml, mcp)."""

from __future__ import annotations

import inspect
from typing import Any

from cantools.database.can import Database
from cantools.database.can.c_source import camel_to_snake_case

from . import config, e2e
from .dbc_checks import cycle_time_ms, e2e_data_id, is_e2e_protected

BANNER = '"""GENERATED by moto-vehicle-defs tools/codegen from {source}. DO NOT EDIT."""\n'


def _py_bytes(values: list[int]) -> str:
    """Python source for a bytes literal, e.g. bytes([0x10, 0x03])."""
    return "bytes([" + ", ".join(f"0x{b:02X}" for b in values) + "])"


def generate_platform_py(db: Database) -> str:
    lines = [BANNER.format(source="dbc/platform.dbc"), ""]
    lines.append("NODE_IDS = {")
    for name, nid in config.NODE_IDS.items():
        lines.append(f'    "{name}": 0x{nid:X},')
    lines += ["}", ""]
    lines.append(f"E2E_TIMEOUT_CYCLES = {config.E2E_TIMEOUT_CYCLES}")
    lines.append(f"E2E_MAX_DELTA_COUNTER = {config.E2E_MAX_DELTA_COUNTER}")
    lines.append("")
    entries = []
    for m in sorted(db.messages, key=lambda m: m.frame_id):
        up = camel_to_snake_case(m.name).upper()
        lines.append(f"{up}_FRAME_ID = 0x{m.frame_id:03X}")
        lines.append(f"{up}_CYCLE_TIME_MS = {cycle_time_ms(m)}")
        data_id = e2e_data_id(m, db) if is_e2e_protected(m, db) else None
        if data_id is not None:
            lines.append(f"{up}_E2E_DATA_ID = 0x{data_id:04X}")
        entries.append(
            f'    "{m.name}": {{"frame_id": 0x{m.frame_id:03X}, "length": {m.length}, '
            f'"cycle_time_ms": {cycle_time_ms(m)}, "sender": "{m.senders[0]}", '
            f'"e2e_data_id": {"None" if data_id is None else f"0x{data_id:04X}"}}},'
        )
    lines += ["", "MESSAGES = {", *entries, "}", ""]
    return "\n".join(lines)


def generate_vehicle_py(vehicle: dict[str, Any]) -> str:
    addr = vehicle["addressing"]
    lines = [BANNER.format(source="uds/vehicle_cl250.yaml"), ""]
    lines.append(f"BITRATE = {vehicle['bus']['bitrate']}")
    lines.append(f"REQUEST_ID = 0x{addr['primary']['request_id']:08X}")
    lines.append(f"RESPONSE_ID = 0x{addr['primary']['response_id']:08X}")
    lines.append(f"FALLBACK_REQUEST_ID = 0x{addr['fallback']['request_id']:03X}")
    lines.append(f"FALLBACK_RESPONSE_ID = 0x{addr['fallback']['response_id']:03X}")
    lines.append(f"FALLBACK_VERIFIED = {bool(addr['fallback']['verified'])}")
    lines.append(f"PADDING_BYTE = 0x{vehicle['transport']['padding_byte']:02X}")
    watch = addr["functional_watch"]["ids"]
    lines.append("# Q-021/D-040: watch-only functional request IDs (id, extended); never sent")
    lines.append(
        "FUNCTIONAL_WATCH_IDS = ("
        + ", ".join(f"(0x{w['id']:X}, {w['id_type'] == 'extended_29bit'})" for w in watch)
        + ",)"
    )
    start = vehicle["session"]["start"]
    tp = vehicle["session"]["tester_present"]
    lines.append(f"SESSION_REQUEST = {_py_bytes(start['request'])}")
    lines.append(f"SESSION_POSITIVE_SID = 0x{start['positive_response_sid']:02X}")
    lines.append(f"SESSION_RETRY_INTERVAL_MS = {start['retry_interval_ms']}")
    lines.append(f"TESTER_PRESENT_REQUEST = {_py_bytes(tp['request'])}")
    lines.append(f"TESTER_PRESENT_PERIOD_MS = {tp['period_ms']}")
    for key in sorted(vehicle["timing"]):
        if key not in ("verified", "evidence"):
            lines.append(f"{key.upper()} = {vehicle['timing'][key]}")
    lines += [
        "",
        "# name -> (did, length, factor_num, factor_den, offset, unit, min, max, poll_ms)",
    ]
    lines.append("DIDS = {")
    for d in vehicle["dids"]:
        lines.append(
            f'    "{d["name"]}": (0x{d["did"]:04X}, {d["length"]}, {d["factor_num"]}, '
            f'{d["factor_den"]}, {d["offset"]}, "{d["unit"]}", {d["min"]}, {d["max"]}, '
            f"{d['poll_period_ms']}),"
        )
    lines += ["}", ""]
    policy = vehicle["tester_policy"]
    allowed = {e["sid"]: e.get("subfunctions") for e in policy["allowed"]}
    lines.append("# D-020: sid -> allowed sub-functions (None = any)")
    lines.append("ALLOWED_SERVICES = {")
    for sid, subs in allowed.items():
        subs_txt = (
            "None" if subs is None else "frozenset({" + ", ".join(f"0x{s:02X}" for s in subs) + "})"
        )
        lines.append(f"    0x{sid:02X}: {subs_txt},")
    lines += ["}", ""]
    lines += [
        "",
        "def decode(name: str, data: bytes) -> float:",
        '    """Physical value of a DID response payload (bytes after the DID echo)."""',
        "    _, length, num, den, offset, _, lo, hi, _, _ = DIDS[name]",
        "    if len(data) < length:",
        '        raise ValueError(f"{name}: need {length} bytes")',
        '    value = int.from_bytes(data[:length], "big") * num / den + offset',
        "    if not lo <= value <= hi:",
        '        raise ValueError(f"{name}: {value} outside [{lo}, {hi}]")',
        "    return value",
        "",
        "",
        "def request_allowed(payload: bytes) -> bool:",
        '    """D-020 allow-list; payload starts with the SID (no ISO-TP PCI)."""',
        "    if not payload or payload[0] not in ALLOWED_SERVICES:",
        "        return False",
        "    subs = ALLOWED_SERVICES[payload[0]]",
        "    if subs is None:",
        "        return True",
        "    return len(payload) >= 2 and (payload[1] & 0x7F) in subs",
        "",
    ]
    return "\n".join(lines)


def generate_e2e_py() -> str:
    source = inspect.getsource(e2e)
    return BANNER.format(source="tools/codegen/src/moto_codegen/e2e.py") + "\n" + source


def generate_init_py() -> str:
    return (
        BANNER.format(source="moto-vehicle-defs")
        + "\n# Modules: platform (platform.dbc constants), vehicle_cl250 (CL250 DIDs),\n"
        "# e2e (reference E2E protect/check), uds (ISO 14229 codes, platform servers).\n"
    )


def generate_limits_py(limits: dict[str, Any]) -> str:
    lines = [BANNER.format(source="limits/platform_limits.yaml"), ""]
    lines.append("# name -> (value, status); rules: limits/platform_limits.yaml")
    lines.append("LIMITS = {")
    for section in ("cornering", "vehicle_speed"):
        for key, entry in limits[section].items():
            lines.append(f'    "{key}": ({entry["value"]!r}, "{entry["status"]}"),')
    lines += ["}", ""]
    return "\n".join(lines)
