"""C output for MCU nodes: gen/c/<node>/.

Per node: cantools pack/unpack for the platform messages the node sends or receives,
message metadata (IDs, cycle times, E2E DataIDs), the E2E protect/check library, and — for
the nodes listed in uds/vehicle_cl250.yaml `c_nodes` — the CL250 DID table with the D-020
request guard. Everything is const data; no dynamic memory, no string parsing.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from cantools.database.can import Database
from cantools.database.can.c_source import camel_to_snake_case
from cantools.database.can.c_source import generate as cantools_generate

from .sources import C_NODES, NODE_IDS, Sources, is_e2e, msg_attr, node_messages
from .templates import E2E_C, E2E_H

BANNER = (
    "/* GENERATED by moto-codegen from moto-vehicle-defs ({src}). Do not edit.\n"
    " * Regenerate with `make gen` in moto-vehicle-defs. */\n"
)
E2E_TIMEOUT_CYCLES = 3  # ARCHITECTURE section 4: receiver timeout = 3 x cycle time


def _strip_timestamp(text: str) -> str:
    # cantools stamps the generation time into the banner; drop it so `make check` is
    # reproducible (the pinned cantools version stays in the banner).
    return re.sub(r"(generated by cantools version [0-9.]+) [^\n]*\.", r"\1.", text)


def _node_db(db: Database, node: str) -> Database:
    return Database(
        messages=node_messages(db, node),
        nodes=db.nodes,
        buses=db.buses,
        version=db.version,
        dbc_specifics=db.dbc,
        strict=True,
    )


def _platform_meta(db: Database, node: str) -> str:
    lines = [
        BANNER.format(src="dbc/platform.dbc"),
        "#ifndef PLATFORM_META_H",
        "#define PLATFORM_META_H",
        "",
    ]
    lines.append("/* Node IDs (ARCHITECTURE section 4). Heartbeat ID = 0x080 + node ID. */")
    for name, nid in NODE_IDS.items():
        lines.append(f"#define PLATFORM_NODE_ID_{name} ({nid}u)")
    lines.append(f"#define PLATFORM_THIS_NODE_ID PLATFORM_NODE_ID_{node}")
    lines.append("")
    lines.append(f"#define PLATFORM_E2E_TIMEOUT_CYCLES ({E2E_TIMEOUT_CYCLES}u)")
    lines.append("")
    for m in node_messages(db, node):
        p = f"PLATFORM_{camel_to_snake_case(m.name).upper()}"
        cycle = msg_attr(m, "GenMsgCycleTime", 0)
        direction = "TX" if node in m.senders else "RX"
        lines.append(f"/* {m.name}: {direction}, sender {m.senders[0]} */")
        lines.append(f"#define {p}_CYCLE_MS ({cycle}u)")
        lines.append(f"#define {p}_E2E_PROTECTED ({1 if is_e2e(m) else 0}u)")
        if is_e2e(m):
            lines.append(f"#define {p}_E2E_DATA_ID ({msg_attr(m, 'E2E_DataID')}u)")
            lines.append(f"#define {p}_E2E_TIMEOUT_MS ({cycle * E2E_TIMEOUT_CYCLES}u)")
        lines.append("")
    lines.append("#endif /* PLATFORM_META_H */")
    return "\n".join(lines) + "\n"


def _c_num(value: float) -> str:
    text = repr(float(value))
    return f"{text}f"


def _vehicle_h(v: dict[str, Any]) -> str:
    p, f = v["addressing"]["primary"], v["addressing"]["fallback"]
    t, s = v["timing"], v["session"]
    out = [
        BANNER.format(src="uds/vehicle_cl250.yaml"),
        "#ifndef VEHICLE_CL250_H",
        "#define VEHICLE_CL250_H",
        "",
    ]
    out += [
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "/* Vehicle bus (D-019). Only the single vehicle-bus tester sends requests (D-021). */",
        f"#define VEHICLE_CL250_BITRATE ({v['bus']['bitrate']}u)",
        f"#define VEHICLE_CL250_FRAME_PADDING (0x{v['bus']['frame_padding']:02X}u)",
        f"#define VEHICLE_CL250_REQUEST_ID (0x{p['request_id']:X}u)",
        f"#define VEHICLE_CL250_RESPONSE_ID (0x{p['response_id']:X}u)",
        f"#define VEHICLE_CL250_ID_IS_EXTENDED ({1 if p['id_type'] == 'extended' else 0}u)",
        f"#define VEHICLE_CL250_FALLBACK_REQUEST_ID (0x{f['request_id']:X}u)",
        f"#define VEHICLE_CL250_FALLBACK_RESPONSE_ID (0x{f['response_id']:X}u)",
        f"#define VEHICLE_CL250_FALLBACK_ID_IS_EXTENDED ({1 if f['id_type'] == 'extended' else 0}u)",
        "",
        "/* UDS service IDs used by the tester. */",
        "#define VEHICLE_CL250_SID_SESSION_CONTROL (0x10u)",
        "#define VEHICLE_CL250_SID_TESTER_PRESENT (0x3Eu)",
        "#define VEHICLE_CL250_SID_READ_DID (0x22u)",
        "#define VEHICLE_CL250_POSITIVE_RESPONSE_OFFSET (0x40u)",
        "#define VEHICLE_CL250_SID_NEGATIVE_RESPONSE (0x7Fu)",
        "#define VEHICLE_CL250_NRC_RESPONSE_PENDING (0x78u)",
        "",
        "/* Session handling and timing (D-019, D-023). */",
        f"#define VEHICLE_CL250_SESSION_SUBFUNCTION (0x{s['request_subfunction']:02X}u)",
        f"#define VEHICLE_CL250_SESSION_RETRY_MS ({s['retry_period_ms']}u)",
        f"#define VEHICLE_CL250_TESTER_PRESENT_SUBFUNCTION (0x{s['tester_present_subfunction']:02X}u)",
        f"#define VEHICLE_CL250_TESTER_PRESENT_PERIOD_MS ({s['tester_present_period_ms']}u)",
        f"#define VEHICLE_CL250_RESPONSE_TIMEOUT_MS ({t['response_timeout_ms']}u)",
        f"#define VEHICLE_CL250_RESPONSE_PENDING_MAX_MS ({t['response_pending_max_ms']}u)",
        f"#define VEHICLE_CL250_MAX_CONSECUTIVE_TIMEOUTS ({t['max_consecutive_timeouts']}u)",
        f"#define VEHICLE_CL250_DID_SKIP_COOLDOWN_MS ({t['did_skip_cooldown_ms']}u)",
        f"#define VEHICLE_CL250_ECU_ABSENT_TIMEOUT_MS ({t['ecu_absent_timeout_ms']}u)",
        f"#define VEHICLE_CL250_BUS_OFF_BACKOFF_MIN_MS ({t['bus_off_backoff_min_ms']}u)",
        f"#define VEHICLE_CL250_BUS_OFF_BACKOFF_MAX_MS ({t['bus_off_backoff_max_ms']}u)",
        "",
        "/* DIDs, in poll-priority order (index = position in vehicle_cl250_dids). */",
    ]
    for i, d in enumerate(v["dids"]):
        out.append(f"#define VEHICLE_CL250_DID_{d['name']} (0x{d['did']:04X}u)")
        out.append(f"#define VEHICLE_CL250_DID_INDEX_{d['name']} ({i}u)")
    out += [
        f"#define VEHICLE_CL250_DID_COUNT ({len(v['dids'])}u)",
        "",
        "typedef struct {",
        "    uint16_t did;",
        "    uint8_t length;          /* data bytes after the echoed DID in the 0x62 response */",
        "    int32_t factor_num;      /* physical = raw * factor_num / factor_den + offset */",
        "    int32_t factor_den;",
        "    float offset;",
        "    float min;",
        "    float max;",
        "    uint16_t poll_period_ms;",
        "    const char *name;        /* for logs only */",
        "    const char *unit;",
        "} vehicle_cl250_did_t;",
        "",
        "extern const vehicle_cl250_did_t vehicle_cl250_dids[VEHICLE_CL250_DID_COUNT];",
        "",
        "/* Table entry for a DID, or NULL if the DID is not defined. */",
        "const vehicle_cl250_did_t *vehicle_cl250_find_did(uint16_t did);",
        "",
        "/* Decodes `len` data bytes (big-endian raw value) into physical units.",
        " * Returns false (and leaves *out untouched) if len is shorter than the DID length. */",
        "bool vehicle_cl250_decode(const vehicle_cl250_did_t *entry, const uint8_t *data, uint8_t len,",
        "                          float *out);",
        "",
        "/* D-020/D-021 frame guard: true only if the complete CAN frame may go on the vehicle",
        " * bus: the ID is the primary or fallback request ID, the frame is an ISO-TP single",
        " * frame (PCI 0x01..0x07, not longer than the DLC) and its UDS request is on the",
        " * allow-list with its minimum length. The tester must call this before every",
        " * transmit. There is deliberately no payload-only variant: without the PCI byte a",
        " * single-frame header 0x01 is indistinguishable from OBD SID 0x01. */",
        "bool vehicle_cl250_frame_allowed(uint32_t can_id, bool is_extended, const uint8_t *frame,",
        "                                 uint8_t dlc);",
        "",
        "/* ISO 14229-1 negative response code name, for logs. */",
        "const char *vehicle_cl250_nrc_name(uint8_t nrc);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* VEHICLE_CL250_H */",
    ]
    return "\n".join(out) + "\n"


def _vehicle_c(v: dict[str, Any]) -> str:
    out = [
        BANNER.format(src="uds/vehicle_cl250.yaml"),
        '#include "vehicle_cl250.h"',
        "",
        "#include <stddef.h>",
        "",
    ]
    out.append("const vehicle_cl250_did_t vehicle_cl250_dids[VEHICLE_CL250_DID_COUNT] = {")
    for d in v["dids"]:
        out.append(
            f"    {{0x{d['did']:04X}u, {d['length']}u, {d['factor_num']}, {d['factor_den']}, "
            f"{_c_num(d['offset'])}, {_c_num(d['min'])}, {_c_num(d['max'])}, "
            f'{d["poll_period_ms"]}u, "{d["name"]}", "{d["unit"]}"}},'
        )
    out += [
        "};",
        "",
        "const vehicle_cl250_did_t *vehicle_cl250_find_did(uint16_t did)",
        "{",
        "    const vehicle_cl250_did_t *found = NULL;",
        "    uint8_t i;",
        "    for (i = 0u; i < VEHICLE_CL250_DID_COUNT; i++) {",
        "        if (vehicle_cl250_dids[i].did == did) {",
        "            found = &vehicle_cl250_dids[i];",
        "            break;",
        "        }",
        "    }",
        "    return found;",
        "}",
        "",
        "bool vehicle_cl250_decode(const vehicle_cl250_did_t *entry, const uint8_t *data, uint8_t len,",
        "                          float *out)",
        "{",
        "    uint32_t raw = 0u;",
        "    uint8_t i;",
        "    if ((entry == NULL) || (data == NULL) || (out == NULL) || (len < entry->length)) {",
        "        return false;",
        "    }",
        "    for (i = 0u; i < entry->length; i++) {",
        "        raw = (raw << 8) | (uint32_t)data[i];",
        "    }",
        "    *out = ((float)raw * (float)entry->factor_num) / (float)entry->factor_den + entry->offset;",
        "    return true;",
        "}",
        "",
        "static bool request_allowed(const uint8_t *request, uint8_t len)",
        "{",
        "    bool allowed = false;",
        "    if ((request != NULL) && (len > 0u)) {",
        "        switch (request[0]) {",
    ]
    for svc in v["allowed_services"]:
        out.append(f"        case 0x{svc['sid']:02X}u: /* {svc['name']} */")
        cond = f"(len >= {svc['min_length']}u)"
        subs = svc.get("subfunctions")
        if subs:
            cond += " && (" + " || ".join(f"(request[1] == 0x{x:02X}u)" for x in subs) + ")"
        out.append(f"            allowed = {cond};")
        out.append("            break;")
    out += [
        "        default:",
        "            allowed = false; /* everything else is forbidden on the vehicle bus (D-020) */",
        "            break;",
        "        }",
        "    }",
        "    return allowed;",
        "}",
        "",
        "bool vehicle_cl250_frame_allowed(uint32_t can_id, bool is_extended, const uint8_t *frame,",
        "                                 uint8_t dlc)",
        "{",
        "    bool id_ok;",
        "    uint8_t sf_len;",
        "    bool allowed = false;",
        "    id_ok = ((can_id == VEHICLE_CL250_REQUEST_ID) &&",
        "             (is_extended == (VEHICLE_CL250_ID_IS_EXTENDED != 0u))) ||",
        "            ((can_id == VEHICLE_CL250_FALLBACK_REQUEST_ID) &&",
        "             (is_extended == (VEHICLE_CL250_FALLBACK_ID_IS_EXTENDED != 0u)));",
        "    if (id_ok && (frame != NULL) && (dlc >= 2u) && (dlc <= 8u) && ((frame[0] & 0xF0u) == 0u)) {",
        "        sf_len = (uint8_t)(frame[0] & 0x0Fu);",
        "        if ((sf_len >= 1u) && (sf_len <= 7u) && (sf_len <= (uint8_t)(dlc - 1u))) {",
        "            allowed = request_allowed(&frame[1], sf_len);",
        "        }",
        "    }",
        "    return allowed;",
        "}",
        "",
        "const char *vehicle_cl250_nrc_name(uint8_t nrc)",
        "{",
        '    const char *name = "unknownNRC";',
        "    switch (nrc) {",
    ]
    for code, name in v["nrc"].items():
        out.append(f'    case 0x{code:02X}u: name = "{name}"; break;')
    out += ["    default: break;", "    }", "    return name;", "}"]
    return "\n".join(out) + "\n"


def generate(src: Sources, out_dir: Path) -> dict[Path, str]:
    files: dict[Path, str] = {}
    vehicle_nodes = set(src.vehicle.get("c_nodes", []))
    for node, dirname in C_NODES.items():
        base = out_dir / "c" / dirname
        db = _node_db(src.platform, node)
        h, c, _, _ = cantools_generate(
            db,
            "platform",
            "platform.h",
            "platform.c",
            "platform_fuzzer.c",
            floating_point_numbers=True,
            use_float=True,
            node_name=node,
        )
        files[base / "platform.h"] = _strip_timestamp(h)
        files[base / "platform.c"] = _strip_timestamp(c)
        files[base / "platform_meta.h"] = _platform_meta(src.platform, node)
        if any(is_e2e(m) for m in db.messages):
            files[base / "moto_e2e.h"] = BANNER.format(src="docs/ARCHITECTURE.md section 4") + E2E_H
            files[base / "moto_e2e.c"] = BANNER.format(src="docs/ARCHITECTURE.md section 4") + E2E_C
        if node in vehicle_nodes:
            files[base / "vehicle_cl250.h"] = _vehicle_h(src.vehicle)
            files[base / "vehicle_cl250.c"] = _vehicle_c(src.vehicle)
    return files
