"""BLE packet schema (`ble/ble_schema.json`, D-061): checks, C macros, Python and Dart.

The JSON is the single source for the telemetry packet (versions 2, 3, 4), the IMU block and
the GATT layout. Consumers (conn, moto-mobile, moto-server) use the generated code instead of
keeping copies. The C output is offset/size macros only: packed structs are a compiler
extension, so conn's own structs `static_assert` against these macros (misra/README.md).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from . import config
from .c_e2e_templates import BANNER as C_BANNER

SOURCE = "ble/ble_schema.json"
PY_BANNER = (
    '"""GENERATED by moto-vehicle-defs tools/codegen from ble/ble_schema.json. DO NOT EDIT."""\n'
)
DART_BANNER = (
    "// GENERATED by moto-vehicle-defs tools/codegen from ble/ble_schema.json. DO NOT EDIT.\n"
    "// Regenerate with `make gen`.\n"
)

TYPE_SIZES = {"uint8": 1, "int8": 1, "uint16": 2, "int16": 2, "uint32": 4, "int32": 4}
# Telemetry fields without `sinceVersion` exist since this version (the layout of D-032).
BASE_VERSION = 3
_NAME = re.compile(r"[a-z][A-Za-z0-9]*")
_UUID = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
# Dart reserved words and built-in identifiers that a field name must not be.
_DART_RESERVED = frozenset(
    "abstract as assert async await break case catch class const continue covariant default "
    "deferred do dynamic else enum export extends extension external factory false final "
    "finally for function get hide if implements import in interface is late library mixin "
    "new null of on operator part required rethrow return sealed set show static super "
    "switch sync this throw true try typedef var void when while with yield".split()
)
_UNIT_NAMES = {"g": "G", "deg/s": "Dps"}  # unit -> identifier part (C upper-cases it)


def load_schema(path: Path | str = config.BLE_SCHEMA) -> dict[str, Any]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: top level must be an object")
    return data


# --- layouts ---------------------------------------------------------------------------


def fields_for_version(schema: dict[str, Any], version: int) -> list[dict[str, Any]]:
    """Telemetry fields that exist in `version` (3 or later; v2 is `lowMtuFallback`)."""
    return [f for f in schema["fields"] if f.get("sinceVersion", BASE_VERSION) <= version]


def telemetry_versions(schema: dict[str, Any]) -> dict[int, int]:
    """version -> total bytes, current layouts only (the fallback is separate), ascending."""
    return {
        int(k): v for k, v in sorted(schema["totalBytesByVersion"].items(), key=lambda i: int(i[0]))
    }


def fallback_version(schema: dict[str, Any]) -> int:
    return schema["lowMtuFallback"]["version"]


def _layouts(schema: dict[str, Any]) -> dict[int, list[dict[str, Any]]]:
    """version -> fields, ascending; includes the low-MTU fallback version."""
    out = {v: fields_for_version(schema, v) for v in telemetry_versions(schema)}
    out[fallback_version(schema)] = schema["lowMtuFallback"]["fields"]
    return dict(sorted(out.items()))


# --- checks ----------------------------------------------------------------------------


def _is_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def _check_layout(label: str, fields: list[dict[str, Any]], total: Any, errors: list[str]) -> None:
    """Fields contiguous from offset 0, type sizes, unique names, end == total."""
    if not isinstance(fields, list) or not fields:
        errors.append(f"ble: {label}: no fields")
        return
    end = 0
    seen: set[str] = set()
    for f in fields:
        name = f.get("name")
        where = f"ble: {label}: field {name!r}"
        if not isinstance(name, str) or not _NAME.fullmatch(name):
            errors.append(f"{where}: name must be lowerCamel [a-z][A-Za-z0-9]*")
        elif name in _DART_RESERVED:
            errors.append(f"{where}: name is a Dart reserved word")
        if name in seen:
            errors.append(f"{where}: duplicate name")
        seen.add(name)
        size, offset, typ = f.get("size"), f.get("offset"), f.get("type")
        if typ not in TYPE_SIZES:
            errors.append(f"{where}: unknown type {typ!r}")
        elif size != TYPE_SIZES[typ]:
            errors.append(f"{where}: size {size} does not match type {typ} ({TYPE_SIZES[typ]})")
        if not _is_int(offset) or not _is_int(size):
            errors.append(f"{where}: offset and size must be integers")
            return
        if offset < end:
            errors.append(f"{where}: offset {offset} overlaps the previous field (ends at {end})")
        elif offset > end:
            errors.append(f"{where}: offset {offset} leaves a gap (previous field ends at {end})")
        end = offset + size
    if end != total:
        errors.append(f"ble: {label}: fields end at {end}, but the declared total is {total}")


def _check_bits(label: str, bits: Any, errors: list[str]) -> None:
    if not isinstance(bits, list) or not bits:
        errors.append(f"ble: {label}: no bits")
        return
    positions: set[int] = set()
    names: set[str] = set()
    for b in bits:
        pos, name = b.get("bit"), b.get("name")
        where = f"ble: {label}: bit {pos!r} ({name!r})"
        if not _is_int(pos) or not 0 <= pos <= 7:
            errors.append(f"{where}: bit position must be an integer 0..7")
        elif pos in positions:
            errors.append(f"{where}: duplicate bit position")
        else:
            positions.add(pos)
        if not isinstance(name, str) or not _NAME.fullmatch(name):
            errors.append(f"{where}: name must be lowerCamel")
        elif name != "reserved" and name in names:
            errors.append(f"{where}: duplicate name")
        elif name in _DART_RESERVED:
            errors.append(f"{where}: name is a Dart reserved word")
        names.add(name)


def _check_telemetry(schema: dict[str, Any], errors: list[str]) -> None:
    version = schema.get("version")
    ver = schema.get("versioning", {})
    totals = schema.get("totalBytesByVersion", {})
    if not _is_int(version) or version < BASE_VERSION:
        errors.append(f"ble: version must be an integer >= {BASE_VERSION}")
        return
    if ver.get("currentVersion") != version:
        errors.append(f"ble: versioning.currentVersion {ver.get('currentVersion')} != version")
    if not totals or not all(k.isdigit() and _is_int(v) for k, v in totals.items()):
        errors.append("ble: totalBytesByVersion must map version strings to byte counts")
        return
    if totals.get(str(version)) != schema.get("totalBytes"):
        errors.append(
            f"ble: totalBytes {schema.get('totalBytes')} != totalBytesByVersion[{version}]"
        )
    # Every field has a valid sinceVersion, in non-decreasing order: each version is a prefix.
    previous = BASE_VERSION
    for f in schema.get("fields", []):
        since = f.get("sinceVersion", BASE_VERSION)
        if not _is_int(since) or not BASE_VERSION <= since <= version:
            errors.append(f"ble: fields: {f.get('name')!r}: sinceVersion {since!r} out of range")
        elif since < previous:
            errors.append(f"ble: fields: {f.get('name')!r}: sinceVersion goes back to {since}")
        else:
            previous = since
    _check_layout("fields", schema.get("fields"), schema.get("totalBytes"), errors)
    for v in sorted(int(k) for k in totals):
        if not BASE_VERSION <= v <= version:
            errors.append(
                f"ble: totalBytesByVersion has version {v} outside {BASE_VERSION}..{version}"
            )
            continue
        _check_layout(
            f"fields as of version {v}", fields_for_version(schema, v), totals[str(v)], errors
        )
    fb = schema.get("lowMtuFallback", {})
    _check_layout("lowMtuFallback.fields", fb.get("fields"), fb.get("totalBytes"), errors)
    # Versions: current and accepted agree with the layouts the schema defines.
    accepted = ver.get("acceptedVersions")
    defined = {int(k) for k in totals} | {fb.get("version")}
    if not isinstance(accepted, list) or set(accepted) != defined:
        errors.append(
            f"ble: acceptedVersions {accepted} != versions with a layout {sorted(defined)}"
        )
    if str(version) not in ver.get("history", {}):
        errors.append(f"ble: versioning.history has no entry for version {version}")
    # The first fields of every layout carry the version and the sequence number.
    for label, fields in (("fields", schema.get("fields")), ("lowMtuFallback", fb.get("fields"))):
        head = [(f.get("name"), f.get("offset")) for f in (fields or [])[:2]]
        if head != [("version", 0), ("seq", 1)]:
            errors.append(f"ble: {label}: must start with version at 0 and seq at 1")
    _check_bits("flags.bits", schema.get("flags", {}).get("bits"), errors)
    health = schema.get("canHealth", {})
    _check_bits("canHealth.canFlags.bits", health.get("canFlags", {}).get("bits"), errors)
    values = health.get("busState", {}).get("values", [])
    codes = [v.get("value") for v in values]
    names = [v.get("name") for v in values]
    if (
        not values
        or not all(_is_int(c) and 0 <= c <= 255 for c in codes)
        or len(set(codes)) != len(codes)
    ):
        errors.append("ble: canHealth.busState.values: codes must be unique integers 0..255")
    if not all(isinstance(n, str) and _NAME.fullmatch(n) for n in names) or len(set(names)) != len(
        names
    ):
        errors.append("ble: canHealth.busState.values: names must be unique lowerCamel")
    if schema.get("notAvailable", {}).get("int16") != -32768:
        errors.append("ble: notAvailable.int16 must be -32768")
    age = schema.get("age", {})
    if age.get("neverReceived") != 65535 or age.get("max") != 65534:
        errors.append("ble: age.neverReceived must be 65535 and age.max 65534")
    if not _is_int(schema.get("notifyPeriodMs")) or schema["notifyPeriodMs"] <= 0:
        errors.append("ble: notifyPeriodMs must be a positive integer")


def _check_imu(schema: dict[str, Any], errors: list[str]) -> None:
    imu = schema.get("imuBlock", {})
    for key in ("version", "headerBytes", "sampleBytes", "maxSamples", "samplePeriodMs",
                "notifyPeriodMs", "totalBytesMax"):  # fmt: skip
        if not _is_int(imu.get(key)) or imu[key] <= 0:
            errors.append(f"ble: imuBlock.{key} must be a positive integer")
            return
    _check_layout("imuBlock.headerFields", imu.get("headerFields"), imu["headerBytes"], errors)
    _check_layout("imuBlock.sampleFields", imu.get("sampleFields"), imu["sampleBytes"], errors)
    expected = imu["headerBytes"] + imu["maxSamples"] * imu["sampleBytes"]
    if imu["totalBytesMax"] != expected:
        errors.append(
            f"ble: imuBlock.totalBytesMax {imu['totalBytesMax']} != headerBytes + maxSamples * "
            f"sampleBytes = {expected}"
        )
    _check_bits("imuBlock.flags.bits", imu.get("flags", {}).get("bits"), errors)
    for sensor in ("accel", "gyro"):
        scale = imu.get("scale", {}).get(sensor, {})
        lsb = scale.get("lsbPerUnit")
        if isinstance(lsb, bool) or not isinstance(lsb, int | float) or lsb <= 0:
            errors.append(f"ble: imuBlock.scale.{sensor}.lsbPerUnit must be a positive number")
        elif scale.get("unit") not in _UNIT_NAMES:
            errors.append(f"ble: imuBlock.scale.{sensor}.unit {scale.get('unit')!r} unknown")


def _check_gatt(schema: dict[str, Any], errors: list[str]) -> None:
    gatt = schema.get("gatt", {})
    uuids = {"serviceUuid": gatt.get("serviceUuid")}
    chars = gatt.get("characteristics", {})
    for name in ("telemetry", "imu", "telematicsRx"):
        uuids[f"characteristics.{name}.uuid"] = chars.get(name, {}).get("uuid")
    for label, uuid in uuids.items():
        if not isinstance(uuid, str) or not _UUID.fullmatch(uuid):
            errors.append(f"ble: gatt.{label}: {uuid!r} is not a lowercase 128-bit UUID")
    if len({u for u in uuids.values() if isinstance(u, str)}) != len(uuids):
        errors.append("ble: gatt: UUIDs must be unique")
    mtu = gatt.get("mtu", {}).get("requested")
    if not _is_int(mtu) or not 23 <= mtu <= 517:
        errors.append("ble: gatt.mtu.requested must be an integer 23..517 (ATT MTU range)")


def check_schema(schema: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for section, check in (
        ("telemetry", _check_telemetry),
        ("imu", _check_imu),
        ("gatt", _check_gatt),
    ):
        try:
            check(schema, errors)
        except (AttributeError, KeyError, TypeError) as exc:  # malformed structure
            errors.append(f"ble: {section}: malformed schema ({type(exc).__name__}: {exc})")
    return errors


# --- naming ----------------------------------------------------------------------------


def _upper_snake(camel: str) -> str:
    """stepGapMaxMs -> STEP_GAP_MAX_MS, rttNrc78Count -> RTT_NRC78_COUNT."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", camel).upper()


def _characteristics(schema: dict[str, Any]) -> dict[str, str]:
    return {k: v["uuid"] for k, v in schema["gatt"]["characteristics"].items()}


def _unit_part(unit: str) -> str:
    return _UNIT_NAMES[unit]


def _scale_int(value: float) -> tuple[int, int]:
    """(raw integer, multiplier) so that value * multiplier is an integer: 65.5 -> (655, 10)."""
    for mult in (1, 10, 100, 1000):
        scaled = value * mult
        if abs(scaled - round(scaled)) < 1e-9:
            return round(scaled), mult
    raise ValueError(f"lsbPerUnit {value} needs more than three decimals")


def _comment(text: str) -> str:
    return text.replace("*/", "* /").replace("/*", "/ *")


# --- C ---------------------------------------------------------------------------------


def generate_c(schema: dict[str, Any]) -> dict[str, str]:
    """gen/c/conn/ble_schema.h: header-only, macros only (no packed structs)."""
    h = [C_BANNER.format(source=SOURCE), "#ifndef BLE_SCHEMA_H", "#define BLE_SCHEMA_H", ""]

    def u(n: int) -> str:
        return f"({n}u)"

    def layout(prefix: str, fields: list[dict[str, Any]], title: str) -> None:
        h.append(f"/* {title} */")
        for f in fields:
            n = f"{prefix}_{_upper_snake(f['name'])}"
            h.append(f"#define {n}_OFFSET {u(f['offset'])} /* {f['type']} */")
            h.append(f"#define {n}_SIZE {u(f['size'])}")
        h.append("")

    def bits(prefix: str, items: list[dict[str, Any]], title: str) -> None:
        h.append(f"/* {title} */")
        for b in items:
            if b["name"] == "reserved":
                continue
            line = f"#define {prefix}_{_upper_snake(b['name'])} (1u << {b['bit']}u)"
            if b.get("description"):
                line += f" /* {_comment(b['description'])} */"
            h.append(line)
        h.append("")

    gatt = schema["gatt"]
    h += [
        "/* BLE packet layouts of moto-connectivity-node (D-061). Offsets are bytes from the",
        " * start of the notification, multi-byte fields are little-endian. No packed structs:",
        " * conn's own structs static_assert against these macros. */",
        "",
        "/* GATT (UUIDs as strings, ATT MTU the central requests) */",
        f'#define BLE_GATT_SERVICE_UUID "{gatt["serviceUuid"]}"',
    ]
    for name, uuid in _characteristics(schema).items():
        h.append(f'#define BLE_GATT_{_upper_snake(name)}_CHAR_UUID "{uuid}"')
    h += [f"#define BLE_GATT_REQUESTED_MTU {u(gatt['mtu']['requested'])}", ""]

    totals = telemetry_versions(schema)
    current, legacy = schema["version"], fallback_version(schema)
    h += [
        "/* Telemetry packet versions: the sender uses CURRENT when the payload limit allows",
        " * its size, else LEGACY (the low-MTU fallback). Older accepted versions are decoded",
        " * by receivers only. */",
        f"#define BLE_TELEMETRY_CURRENT_VERSION {u(current)}",
        f"#define BLE_TELEMETRY_LEGACY_VERSION {u(legacy)}",
    ]
    for v, total in totals.items():
        h.append(f"#define BLE_TELEMETRY_V{v}_TOTAL_BYTES {u(total)}")
    h.append(
        f"#define BLE_TELEMETRY_V{legacy}_TOTAL_BYTES {u(schema['lowMtuFallback']['totalBytes'])}"
    )
    h += [
        f"#define BLE_TELEMETRY_NOTIFY_PERIOD_MS {u(schema['notifyPeriodMs'])}",
        "",
        "/* Not-available and age sentinels */",
        f"#define BLE_TELEMETRY_NOT_AVAILABLE_INT16 ({schema['notAvailable']['int16']})",
        f"#define BLE_TELEMETRY_AGE_NEVER_RECEIVED {u(schema['age']['neverReceived'])}",
        f"#define BLE_TELEMETRY_AGE_MAX {u(schema['age']['max'])}",
        "",
    ]
    layout(
        f"BLE_TELEMETRY_V{current}",
        fields_for_version(schema, current),
        f"Telemetry version {current} layout ({totals[current]} bytes)",
    )
    layout(
        f"BLE_TELEMETRY_V{legacy}",
        schema["lowMtuFallback"]["fields"],
        f"Telemetry version {legacy} layout, the low-MTU fallback "
        f"({schema['lowMtuFallback']['totalBytes']} bytes)",
    )
    bits("BLE_TELEMETRY_FLAG", schema["flags"]["bits"], "Telemetry `flags` bits")
    bits("BLE_CAN_FLAG", schema["canHealth"]["canFlags"]["bits"], "Telemetry `canFlags` bits")
    h.append("/* Telemetry `canBusState` values */")
    for v in schema["canHealth"]["busState"]["values"]:
        line = f"#define BLE_CAN_BUS_STATE_{_upper_snake(v['name'])} {u(v['value'])}"
        if v.get("description"):
            line += f" /* {_comment(v['description'])} */"
        h.append(line)
    h.append("")

    imu = schema["imuBlock"]
    h += [
        "/* IMU block (characteristic `imu`) */",
        f"#define BLE_IMU_BLOCK_VERSION {u(imu['version'])}",
        f"#define BLE_IMU_HEADER_BYTES {u(imu['headerBytes'])}",
        f"#define BLE_IMU_SAMPLE_BYTES {u(imu['sampleBytes'])}",
        f"#define BLE_IMU_MAX_SAMPLES {u(imu['maxSamples'])}",
        f"#define BLE_IMU_SAMPLE_PERIOD_MS {u(imu['samplePeriodMs'])}",
        f"#define BLE_IMU_NOTIFY_PERIOD_MS {u(imu['notifyPeriodMs'])}",
        f"#define BLE_IMU_TOTAL_BYTES_MAX {u(imu['totalBytesMax'])}",
        "",
        "/* IMU raw scale: physical = raw / LSB_PER_<unit>. An LSB value that is not an",
        " * integer is given times the multiplier in the macro name (X10 = tenths), so the",
        " * header holds integer constants only; the exact value is in ble_schema.json. */",
    ]
    for sensor in ("accel", "gyro"):
        scale = imu["scale"][sensor]
        raw, mult = _scale_int(scale["lsbPerUnit"])
        suffix = "" if mult == 1 else f"_X{mult}"
        unit = _unit_part(scale["unit"]).upper()
        h.append(f"#define BLE_IMU_{sensor.upper()}_LSB_PER_{unit}{suffix} {u(raw)}")
    h.append("")
    layout("BLE_IMU_HEADER", imu["headerFields"], f"IMU header ({imu['headerBytes']} bytes)")
    layout("BLE_IMU_SAMPLE", imu["sampleFields"], f"IMU sample ({imu['sampleBytes']} bytes)")
    bits("BLE_IMU_FLAG", imu["flags"]["bits"], "IMU header `flags` bits")
    h += ["#endif /* BLE_SCHEMA_H */", ""]
    return {"ble_schema.h": "\n".join(h)}


# --- Python ----------------------------------------------------------------------------


def _py_scalar(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    return repr(value)


def _py_literal(value: Any, indent: int = 0) -> str:
    """Deterministic Python literal: flat containers on one line, nested ones expanded."""
    pad = "    " * (indent + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        flat = not any(isinstance(v, dict | list) for v in value.values())
        if flat:
            return (
                "{" + ", ".join(f"{json.dumps(k)}: {_py_scalar(v)}" for k, v in value.items()) + "}"
            )
        rows = [f"{pad}{json.dumps(k)}: {_py_literal(v, indent + 1)}," for k, v in value.items()]
        return "{\n" + "\n".join(rows) + "\n" + "    " * indent + "}"
    if isinstance(value, list):
        if not any(isinstance(v, dict | list) for v in value):
            return "[" + ", ".join(_py_scalar(v) for v in value) + "]"
        rows = [f"{pad}{_py_literal(v, indent + 1)}," for v in value]
        return "[\n" + "\n".join(rows) + "\n" + "    " * indent + "]"
    return _py_scalar(value)


def generate_python(schema: dict[str, Any]) -> str:
    totals = telemetry_versions(schema)
    lines = [
        PY_BANNER,
        "",
        "# The full schema, as in ble/ble_schema.json (moto-server decodes from it).",
        f"SCHEMA = {_py_literal(schema)}",
        "",
        f"CURRENT_VERSION = {schema['version']}",
        f"ACCEPTED_VERSIONS = {tuple(schema['versioning']['acceptedVersions'])!r}",
        f"FALLBACK_VERSION = {fallback_version(schema)}",
        f"TOTAL_BYTES = {schema['totalBytes']}",
        "# Current layouts by version; the low-MTU fallback is FALLBACK_VERSION.",
        "TOTAL_BYTES_BY_VERSION = {" + ", ".join(f"{v}: {t}" for v, t in totals.items()) + "}",
        f"FALLBACK_TOTAL_BYTES = {schema['lowMtuFallback']['totalBytes']}",
        "",
        "",
        "def telemetry_fields(version: int) -> list[dict]:",
        '    """Field table of a telemetry layout; ValueError for a version without one."""',
        "    if version == FALLBACK_VERSION:",
        '        return SCHEMA["lowMtuFallback"]["fields"]',
        "    if version not in TOTAL_BYTES_BY_VERSION:",
        '        raise ValueError(f"no telemetry layout for version {version}")',
        '    return [f for f in SCHEMA["fields"] if f.get("sinceVersion", 3) <= version]',
        "",
    ]
    return "\n".join(lines)


# --- Dart ------------------------------------------------------------------------------


def _dart_str(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    return f"'{escaped}'"


def _dart_doc(text: str) -> str:
    return f"  /// {text}\n"


def generate_dart(schema: dict[str, Any]) -> dict[str, str]:
    out: list[str] = [DART_BANNER]
    current, legacy = schema["version"], fallback_version(schema)
    totals = telemetry_versions(schema)

    def cls(name: str, doc: str, members: list[tuple[str, str, str, str]]) -> None:
        """members: (type, name, value literal, doc)."""
        out.append(f"/// {doc}")
        out.append(f"abstract final class {name} {{")
        for typ, member, value, mdoc in members:
            if mdoc:
                out.append(_dart_doc(_comment_dart(mdoc)).rstrip("\n"))
            out.append(f"  static const {typ} {member} = {value};")
        out.append("}")
        out.append("")

    def offsets(name: str, doc: str, fields: list[dict[str, Any]], key: str) -> None:
        cls(
            name,
            doc,
            [("int", f["name"], str(f[key]), f.get("description", "")) for f in fields],
        )

    def flag_bits(name: str, doc: str, items: list[dict[str, Any]]) -> None:
        cls(
            name,
            doc,
            [
                ("int", b["name"], f"1 << {b['bit']}", b.get("description", ""))
                for b in items
                if b["name"] != "reserved"
            ],
        )

    gatt = schema["gatt"]
    members = [("String", "serviceUuid", _dart_str(gatt["serviceUuid"]), "")]
    for name, uuid in _characteristics(schema).items():
        members.append(("String", f"{name}CharacteristicUuid", _dart_str(uuid), ""))
    members.append(
        ("int", "requestedMtu", str(gatt["mtu"]["requested"]), "ATT MTU the central requests.")
    )
    cls("BleGatt", "GATT service and characteristic UUIDs and the requested ATT MTU.", members)

    members = [
        ("int", "currentVersion", str(current), "Version the sender produces."),
        ("int", "legacyVersion", str(legacy), "Low-MTU fallback version."),
        (
            "List<int>",
            "acceptedVersions",
            "<int>[" + ", ".join(str(v) for v in schema["versioning"]["acceptedVersions"]) + "]",
            "Versions a receiver decodes.",
        ),
        ("int", "totalBytes", str(schema["totalBytes"]), "Size of the current version."),
    ]
    for v, total in totals.items():
        members.append(("int", f"totalBytesV{v}", str(total), f"Size of version {v}."))
    members += [
        (
            "int",
            f"totalBytesV{legacy}",
            str(schema["lowMtuFallback"]["totalBytes"]),
            f"Size of version {legacy}.",
        ),
        ("int", "notifyPeriodMs", str(schema["notifyPeriodMs"]), ""),
        (
            "int",
            "notAvailableInt16",
            str(schema["notAvailable"]["int16"]),
            "Lean fields: no value.",
        ),
        (
            "int",
            "ageNeverReceived",
            str(schema["age"]["neverReceived"]),
            "Age: no value since boot.",
        ),
        ("int", "ageMax", str(schema["age"]["max"]), "Age saturates here."),
    ]
    cls("BleTelemetry", "Telemetry packet versions and sizes.", members)

    for v, fields in _layouts(schema).items():
        for key, kind in (("offset", "Offsets"), ("size", "Sizes")):
            offsets(
                f"BleTelemetryV{v}{kind}",
                f"Telemetry version {v}: byte {key} of each field (little-endian).",
                fields,
                key,
            )
    flag_bits("BleTelemetryFlagBits", "Telemetry `flags` bit masks.", schema["flags"]["bits"])
    flag_bits(
        "BleCanFlagsBits",
        "Telemetry `canFlags` bit masks.",
        schema["canHealth"]["canFlags"]["bits"],
    )
    cls(
        "BleCanBusState",
        "Telemetry `canBusState` values.",
        [
            ("int", v["name"], str(v["value"]), v.get("description", ""))
            for v in schema["canHealth"]["busState"]["values"]
        ],
    )

    imu = schema["imuBlock"]
    cls(
        "BleImuBlock",
        "IMU block format (characteristic `imu`).",
        [
            ("int", "version", str(imu["version"]), ""),
            ("int", "headerBytes", str(imu["headerBytes"]), ""),
            ("int", "sampleBytes", str(imu["sampleBytes"]), ""),
            ("int", "maxSamples", str(imu["maxSamples"]), ""),
            ("int", "samplePeriodMs", str(imu["samplePeriodMs"]), ""),
            ("int", "notifyPeriodMs", str(imu["notifyPeriodMs"]), ""),
            ("int", "totalBytesMax", str(imu["totalBytesMax"]), ""),
        ],
    )
    for key, kind in (("offset", "Offsets"), ("size", "Sizes")):
        offsets(
            "BleImuHeader" + kind,
            f"IMU header: byte {key} of each field.",
            imu["headerFields"],
            key,
        )
        offsets(
            "BleImuSample" + kind,
            f"IMU sample: byte {key} of each field.",
            imu["sampleFields"],
            key,
        )
    flag_bits("BleImuFlagBits", "IMU header `flags` bit masks.", imu["flags"]["bits"])
    members = []
    for sensor in ("accel", "gyro"):
        scale = imu["scale"][sensor]
        lsb = float(scale["lsbPerUnit"])
        members.append(
            (
                "double",
                f"{sensor}LsbPer{_unit_part(scale['unit'])}",
                repr(lsb),
                f"physical ({scale['unit']}) = raw / this value.",
            )
        )
    cls("BleImuScale", "IMU raw scale (D-032, provisional sensor).", members)

    pubspec = (
        "# GENERATED by moto-vehicle-defs tools/codegen from ble/ble_schema.json. DO NOT EDIT.\n"
        "name: moto_defs\n"
        "description: BLE packet layout of moto-connectivity-node, generated from "
        "moto-vehicle-defs ble/ble_schema.json (D-061).\n"
        "publish_to: none\n"
        "environment:\n"
        '  sdk: ">=3.0.0 <4.0.0"\n'
    )
    barrel = DART_BANNER + "\nexport 'ble_schema.dart';\n"
    return {
        "pubspec.yaml": pubspec,
        "lib/ble_schema.dart": "\n".join(out).rstrip("\n") + "\n",
        "lib/moto_defs.dart": barrel,
    }


def _comment_dart(text: str) -> str:
    return text.replace("\n", " ")
